# SQL CARTO QUERY FUNCTION
# written for PUI2016_Python2

##### This notebook is set up to link as a default to the fb55 account.  To turn in the homework use the citibike dataset - check that you are able to read in about 40k rows

In [1]:
SQL_SOURCE = 'https://fb55.carto.com/api/v2/sql?q='

import urllib2
import urllib
import StringIO
import ast
import pandas as pd

def queryCartoDB(query, format='CSV', source=SQL_SOURCE):
    '''queries carto datasets from a given carto account
    Arguments: 
    query - string: a valid sql query string
    format - outlut format  OPTIONAL (default CSV)
    source - a valid sql api endpoint OPTIONAL (default carto fb55 account)
    Returns:
    the return of the sql query AS A STRING
    NOTES:
    designed for the carto API, tested only with CSV return format'''
    
    data = urllib.urlencode({'format': format, 'q': query})
    try:
        response = urllib2.urlopen(source, data)
    except urllib2.HTTPError, e:
        raise ValueError('\n'.join(ast.literal_eval(e.readline())['error']))
    except Exception:
        raise
    return response.read()

In [2]:
test = '''
SELECT *
FROM htv210.citibike_feb_2015
'''

In [3]:
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

,the_geom,start_station_longitude,the_geom_webmercator,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,cartodb_id,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,-73.993934,NaN,447,2015-02-01 01:11:00+00,2015-02-01 01:19:00+00,490,8 Ave & W 33 St,40.751551,93,479,9 Ave & W 45 St,40.760193,-73.991255,15185,Subscriber,1983.0,2
1,NaN,-73.987216,NaN,277,2015-02-01 10:26:00+00,2015-02-01 10:30:00+00,533,Broadway & W 39 St,40.752996,847,515,W 43 St & 10 Ave,40.760094,-73.994618,16452,Subscriber,1978.0,1
2,NaN,-73.994564,NaN,526,2015-02-01 11:07:00+00,2015-02-01 11:16:00+00,168,W 18 St & 6 Ave,40.739713,1180,521,8 Ave & W 31 St,40.750450,-73.994811,16741,Subscriber,1984.0,1
3,NaN,-73.989551,NaN,502,2015-02-01 12:37:00+00,2015-02-01 12:46:00+00,402,Broadway & E 22 St,40.740343,1971,459,W 20 St & 11 Ave,40.746745,-74.007756,16951,Subscriber,1983.0,1
4,NaN,-73.996674,NaN,943,2015-02-01 12:46:00+00,2015-02-01 13:02:00+00,508,W 46 St & 11 Ave,40.763414,2053,521,8 Ave & W 31 St,40.750450,-73.994811,16897,Subscriber,1966.0,2
5,NaN,-73.993790,NaN,563,2015-02-01 12:54:00+00,2015-02-01 13:03:00+00,229,Great Jones St,40.727434,2138,346,Bank St & Hudson St,40.736529,-74.006180,16722,Subscriber,1984.0,1
6,NaN,-74.002150,NaN,519,2015-02-01 15:21:00+00,2015-02-01 15:29:00+00,368,Carmine St & 6 Ave,40.730386,3591,503,E 20 St & Park Ave,40.738274,-73.987520,15196,Subscriber,1968.0,1
7,NaN,-73.988900,NaN,500,2015-02-01 17:38:00+00,2015-02-01 17:47:00+00,483,E 12 St & 3 Ave,40.732233,4983,435,W 21 St & 6 Ave,40.741740,-73.994156,19409,Customer,NaN,0
8,NaN,-73.997262,NaN,374,2015-02-01 17:48:00+00,2015-02-01 17:55:00+00,334,W 20 St & 7 Ave,40.742388,5067,497,E 17 St & Broadway,40.737050,-73.990093,21456,Customer,NaN,0
9,NaN,-73.984267,NaN,420,2015-02-01 19:26:00+00,2015-02-01 19:33:00+00,326,E 11 St & 1 Ave,40.729538,5748,527,E 33 St & 2 Ave,40.744023,-73.976056,14878,Subscriber,1988.0,1
10,NaN,-73.995299,NaN,315,2015-02-01 21:34:00+00,2015-02-01 21:39:00+00,446,W 24 St & 7 Ave,40.744876,6086,521,8 Ave & W 31 St,40.750450,-73.994811,16042,Subscriber,1956.0,1
11,NaN,-73.979955,NaN,1312,2015-02-02 11:07:00+00,2015-02-02 11:29:00+00,393,E 5 St & Avenue C,40.722992,6920,476,E 31 St & 3 Ave,40.743943,-73.979661,17720,Subscriber,1955.0,1
12,NaN,-73.981632,NaN,360,2015-02-03 10:33:00+00,2015-02-03 10:39:00+00,153,E 40 St & 5 Ave,40.752062,9070,523,W 38 St & 8 Ave,40.754666,-73.991382,19432,Subscriber,1975.0,1
13,NaN,-73.994156,NaN,617,2015-02-03 12:51:00+00,2015-02-03 13:01:00+00,435,W 21 St & 6 Ave,40.741740,9442,462,W 22 St & 10 Ave,40.746920,-74.004519,15457,Subscriber,1987.0,2
14,NaN,-73.984907,NaN,233,2015-02-03 16:55:00+00,2015-02-03 16:59:00+00,526,E 33 St & 5 Ave,40.747659,10478,492,W 33 St & 7 Ave,40.750200,-73.990931,17873,Subscriber,1978.0,1
15,NaN,-73.980420,NaN,768,2015-02-03 17:27:00+00,2015-02-03 17:39:00+00,510,W 51 St & 6 Ave,40.760660,10769,492,W 33 St & 7 Ave,40.750200,-73.990931,15552,Subscriber,1977.0,1
16,NaN,-73.966033,NaN,392,2015-02-03 17:44:00+00,2015-02-03 17:50:00+00,385,E 55 St & 2 Ave,40.757973,10930,2022,E 59 St & Sutton Pl,40.758491,-73.959206,20994,Subscriber,1989.0,1
17,NaN,-73.986831,NaN,647,2015-02-03 18:01:00+00,2015-02-03 18:12:00+00,474,5 Ave & E 29 St,40.745168,11095,465,Broadway & W 41 St,40.755136,-73.986580,15740,Subscriber,1983.0,1
18,NaN,-74.002939,NaN,3589,2015-02-03 19:55:00+00,2015-02-03 20:55:00+00,380,W 4 St & 7 Ave S,40.734011,11966,441,E 52 St & 2 Ave,40.756014,-73.967416,18079,Customer,NaN,0
19,NaN,-73.980572,NaN,319,2015-02-03 19:55:00+00,2015-02-03 20:01:00+00,433,E 13 St & Avenue A,40.729554,11971,410,Suffolk St & Stanton St,40.720664,-73.985180,17595,Subscriber,1990.0,1
20,NaN,-73.976056,NaN,538,2015-02-04 07:58:00+00,2015-02-04 08:07:00+00,527,E 33 St & 2 Ave,40.744023,13543,516,E 47 St & 1 Ave,40.752069,-73.967844,20322,Subscriber,1976.0,2
21,NaN,-73.990026,NaN,883,2015-02-04 08:15:00+00,2015-02-04 08:30:00+00,477,W 41 St & 8 Ave,40.756405,13760,168,W 18 St & 6 Ave,40.739713,-73.994564,21186,Subscriber,1981.0,1
22,NaN,-73.990026,NaN,583,2015-02-04 08:37:00+00,2015-02-04 08:46:00+00,477,W 41 St & 8 Ave,40.756405,14055,518,E 39 St & 2 Ave,40.747804,-73.973442,21285,Subscriber,1985.0,1
23,NaN,-73.982912,NaN,966,2015-02-04 08:46:00+00,2015-02-04 09:02:00+00,493,W 45 St & 6 Ave,40.756800,14181,454,E 51 St & 1 Ave,40.754557,-73.965930,21462,Subscriber,1964.0,1
24,NaN,-73.977061,NaN,496,2015-02-04 09:13:00+00,2015-02-04 09:22:00+00,528,2 Ave & E 31 St,40.742909,14573,486,Broadway & W 29 St,40.746201,-73.988557,19977,Subscriber,1959.0,1
25,NaN,-73.994156,NaN,353,2015-02-04 11:58:00+00,2015-02-04 12:04:00+00,435,W 21 St & 6 Ave,40.741740,15658,463,9 Ave & W 16 St,40.742065,-74.004432,16097,Subscriber,1972.0,1
26,NaN,-73.977910,NaN,707,2015-02-04 17:56:00+00,2015-02-04 18:08:00+00,517,Pershing Square South,40.751581,18779,2022,E 59 St & Sutton Pl,40.758491,-73.959206,18134,Subscriber,1978.0,1
27,NaN,-73.964785,NaN,351,2015-02-04 19:12:00+00,2015-02-04 19:18:00+00,290,2 Ave & E 58 St,40.760203,19945,518,E 39 St & 2 Ave,40.747804,-73.973442,15196,Subscriber,1972.0,1
28,NaN,-73.990985,NaN,191,2015-02-04 22:27:00+00,2015-02-04 22:30:00+00,529,W 42 St & 8 Ave,40.757570,21359,478,11 Ave & W 41 St,40.760301,-73.998842,20097,Subscriber,1971.0,1
29,NaN,-73.990931,NaN,159,2015-02-05 05:42:00+00,2015-02-05 05:44:00+00,492,W 33 St & 7 Ave,40.750200,21821,442,W 27 St & 7 Ave,40.746647,-73.993915,16199,Subscriber,1968.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46170,NaN,-73.994046,NaN,812,2015-02-07 23:51:00+00,2015-02-08 00:05:00+00,335,Washington Pl & Broadway,40.729039,46171,435,W 21 St & 6 Ave,40.741740,-73.994156,15733,Subscriber,1988.0,1
46171,NaN,-73.991908,NaN,647,2015-02-07 23:51:00+00,2015-02-08 00:02:00+00,361,Allen St & Hester St,40.716059,46172,504,1 Ave & E 15 St,40.732219,-73.981656,16931,Subscriber,1995.0,1
46172,NaN,-74.009106,NaN,563,2015-02-07 23:51:00+00,2015-02-08 00:00:00+00,152,Warren St & Church St,40.714740,46173,401,Allen St & Rivington St,40.720196,-73.989978,17202,Subscriber,1987.0,1
46173,NaN,-73.988900,NaN,470,2015-02-07 23:51:00+00,2015-02-07 23:59:00+00,483,E 12 St & 3 Ave,40.732233,46174,439,E 4 St & 2 Ave,40.726281,-73.989780,20314,Subscriber,1989.0,2
46174,NaN,-73.978951,NaN,299,2015-02-07 23:51:00+00,2015-02-07 23:56:00+00,467,Dean St & 4 Ave,40.683125,46175,395,Bond St & Schermerhorn St,40.688070,-73.984106,21531,Subscriber,1989.0,1
46175,NaN,-73.991908,NaN,629,2015-02-07 23:52:00+00,2015-02-08 00:02:00+00,361,Allen St & Hester St,40.716059,46176,504,1 Ave & E 15 St,40.732219,-73.981656,21491,Subscriber,1968.0,1
46176,NaN,-73.989551,NaN,499,2015-02-07 23:52:00+00,2015-02-08 00:00:00+00,402,Broadway & E 22 St,40.740343,46177,380,W 4 St & 7 Ave S,40.734011,-74.002939,15367,Subscriber,1990.0,1
46177,NaN,-74.000264,NaN,474,2015-02-07 23:52:00+00,2015-02-08 00:00:00+00,369,Washington Pl & 6 Ave,40.732241,46178,368,Carmine St & 6 Ave,40.730386,-74.002150,18978,Subscriber,1973.0,2
46178,NaN,-73.979661,NaN,345,2015-02-07 23:52:00+00,2015-02-07 23:58:00+00,476,E 31 St & 3 Ave,40.743943,46179,504,1 Ave & E 15 St,40.732219,-73.981656,19507,Subscriber,1980.0,1
46179,NaN,-73.981918,NaN,829,2015-02-07 23:53:00+00,2015-02-08 00:07:00+00,499,Broadway & W 60 St,40.769155,46180,160,E 37 St & Lexington Ave,40.748238,-73.978311,16936,Subscriber,1980.0,1
46180,NaN,-74.002150,NaN,776,2015-02-07 23:53:00+00,2015-02-08 00:05:00+00,368,Carmine St & 6 Ave,40.730386,46181,531,Forsyth St & Broome St,40.718939,-73.992663,18689,Subscriber,1982.0,1
46181,NaN,-73.976485,NaN,697,2015-02-07 23:53:00+00,2015-02-08 00:05:00+00,520,W 52 St & 5 Ave,40.759923,46182,478,11 Ave & W 41 St,40.760301,-73.998842,15781,Subscriber,1972.0,1
46182,NaN,-73.978951,NaN,1703,2015-02-07 23:54:00+00,2015-02-08 00:23:00+00,467,Dean St & 4 Ave,40.683125,46183,471,Grand St & Havemeyer St,40.712868,-73.956981,15081,Subscriber,1988.0,1
46183,NaN,-73.991255,NaN,922,2015-02-07 23:54:00+00,2015-02-08 00:10:00+00,479,9 Ave & W 45 St,40.760193,46184,247,Perry St & Bleecker St,40.735354,-74.004831,21672,Subscriber,1983.0,1
46184,NaN,-73.981693,NaN,849,2015-02-07 23:54:00+00,2015-02-08 00:08:00+00,457,Broadway & W 58 St,40.766953,46185,488,W 39 St & 9 Ave,40.756458,-73.993722,16336,Subscriber,1970.0,1
46185,NaN,-73.981693,NaN,826,2015-02-07 23:54:00+00,2015-02-08 00:08:00+00,457,Broadway & W 58 St,40.766953,46186,488,W 39 St & 9 Ave,40.756458,-73.993722,21609,Subscriber,1973.0,1
46186,NaN,-74.009660,NaN,473,2015-02-07 23:54:00+00,2015-02-08 00:02:00+00,328,Watts St & Greenwich St,40.724055,46187,3002,South End Ave & Liberty St,40.711512,-74.015756,19470,Subscriber,1964.0,1
46187,NaN,-73.980420,NaN,332,2015-02-07 23:54:00+00,2015-02-07 23:59:00+00,510,W 51 St & 6 Ave,40.760660,46188,450,W 49 St & 8 Ave,40.762272,-73.987882,18167,Subscriber,1960.0,1
46188,NaN,-73.992005,NaN,456,2015-02-07 23:55:00+00,2015-02-08 00:03:00+00,382,University Pl & E 14 St,40.734927,46189,404,9 Ave & W 14 St,40.740583,-74.005509,15929,Subscriber,1987.0,1
46189,NaN,-73.998004,NaN,327,2015-02-07 23:55:00+00,2015-02-08 00:01:00+00,254,W 11 St & 6 Ave,40.735324,46190,466,W 25 St & 6 Ave,40.743954,-73.991449,17541,Subscriber,1983.0,1
46190,NaN,-74.001497,NaN,306,2015-02-07 23:55:00+00,2015-02-08 00:01:00+00,116,W 17 St & 8 Ave,40.741776,46191,494,W 26 St & 8 Ave,40.747348,-73.997236,14736,Subscriber,1983.0,2
46191,NaN,-73.993012,NaN,1248,2015-02-07 23:56:00+00,2015-02-08 00:17:00+00,495,W 47 St & 10 Ave,40.762699,46192,432,E 7 St & Avenue A,40.726218,-73.983799,16300,Subscriber,1984.0,1
46192,NaN,-74.009106,NaN,1165,2015-02-07 23:56:00+00,2015-02-08 00:15:00+00,152,Warren St & Church St,40.714740,46193,325,E 19 St & 3 Ave,40.736245,-73.984738,16978,Subscriber,1959.0,1
46193,NaN,-73.982050,NaN,993,2015-02-07 23:56:00+00,2015-02-08 00:13:00+00,461,E 20 St & 2 Ave,40.735877,46194,295,Pike St & E Broadway,40.714067,-73.992939,16722,Subscriber,1974.0,1
46194,NaN,-73.969053,NaN,1422,2015-02-07 23:57:00+00,2015-02-08 00:20:00+00,455,1 Ave & E 44 St,40.750020,46195,265,Stanton St & Chrystie St,40.722293,-73.991475,20184,Subscriber,1960.0,2
46195,NaN,-74.000040,NaN,689,2015-02-07 23:57:00+00,2015-02-08 00:08:00+00,470,W 20 St & 8 Ave,40.743453,46196,325,E 19 St & 3 Ave,40.736245,-73.984738,15585,Subscriber,1953.0,1
46196,NaN,-73.986831,NaN,428,2015-02-07 23:57:00+00,2015-02-08 00:04:00+00,474,5 Ave & E 29 St,40.745168,46197,325,E 19 St & 3 Ave,40.736245,-73.984738,16395,Subscriber,1986.0,2
46197,NaN,-73.986831,NaN,392,2015-02-07 23:57:00+00,2015-02-08 00:03:00+00,474,5 Ave & E 29 St,40.745168,46198,325,E 19 St & 3 Ave,40.736245,-73.984738,15545,Subscriber,1986.0,1
46198,NaN,-74.002150,NaN,548,2015-02-07 23:58:00+00,2015-02-08 00:08:00+00,368,Carmine St & 6 Ave,40.730386,46199,334,W 20 St & 7 Ave,40.742388,-73.997262,19540,Subscriber,1983.0,2
46199,NaN,-73.989780,NaN,917,2015-02-07 23:59:00+00,2015-02-08 00:15:00+00,439,E 4 St & 2 Ave,40.726281,46200,417,Barclay St & Church St,40.712912,-74.010202,20998,Subscriber,1965.0,2

## Task 1 — Familiarize with SQL Clauses
### 1) Sort data by start_station_id, tripduration¶
### Only checking trips with duration <= 3hours

In [4]:
test = '''SELECT * FROM htv210.citibike_feb_2015 
WHERE tripduration <= 10800 
ORDER BY start_station_id, tripduration DESC'''
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

,the_geom,start_station_longitude,the_geom_webmercator,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,cartodb_id,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,-73.993929,NaN,2099,2015-02-03 10:28:00+00,2015-02-03 11:02:00+00,72,W 52 St & 11 Ave,40.767272,9054,328,Watts St & Greenwich St,40.724055,-74.009660,18653,Subscriber,1966.0,2
1,NaN,-73.993929,NaN,1944,2015-02-01 12:39:00+00,2015-02-01 13:12:00+00,72,W 52 St & 11 Ave,40.767272,1983,328,Watts St & Greenwich St,40.724055,-74.009660,17849,Customer,NaN,0
2,NaN,-73.993929,NaN,1914,2015-02-07 09:49:00+00,2015-02-07 10:21:00+00,72,W 52 St & 11 Ave,40.767272,40341,328,Watts St & Greenwich St,40.724055,-74.009660,21520,Subscriber,1966.0,2
3,NaN,-73.993929,NaN,1801,2015-02-04 06:32:00+00,2015-02-04 07:02:00+00,72,W 52 St & 11 Ave,40.767272,12938,328,Watts St & Greenwich St,40.724055,-74.009660,15161,Subscriber,1959.0,2
4,NaN,-73.993929,NaN,1678,2015-02-03 18:21:00+00,2015-02-03 18:49:00+00,72,W 52 St & 11 Ave,40.767272,11298,79,Franklin St & W Broadway,40.719116,-74.006667,21500,Subscriber,1964.0,1
5,NaN,-73.993929,NaN,1537,2015-02-04 08:07:00+00,2015-02-04 08:33:00+00,72,W 52 St & 11 Ave,40.767272,13647,487,E 20 St & FDR Drive,40.733143,-73.975739,18900,Subscriber,1977.0,2
6,NaN,-73.993929,NaN,1535,2015-02-03 14:23:00+00,2015-02-03 14:48:00+00,72,W 52 St & 11 Ave,40.767272,9742,334,W 20 St & 7 Ave,40.742388,-73.997262,15117,Subscriber,1956.0,2
7,NaN,-73.993929,NaN,1518,2015-02-03 18:16:00+00,2015-02-03 18:42:00+00,72,W 52 St & 11 Ave,40.767272,11240,476,E 31 St & 3 Ave,40.743943,-73.979661,19039,Subscriber,1971.0,1
8,NaN,-73.993929,NaN,1493,2015-02-04 19:47:00+00,2015-02-04 20:12:00+00,72,W 52 St & 11 Ave,40.767272,20309,79,Franklin St & W Broadway,40.719116,-74.006667,21080,Subscriber,1964.0,1
9,NaN,-73.993929,NaN,1388,2015-02-05 10:34:00+00,2015-02-05 10:58:00+00,72,W 52 St & 11 Ave,40.767272,24953,127,Barrow St & Hudson St,40.731724,-74.006744,19672,Subscriber,1974.0,1
10,NaN,-73.993929,NaN,1382,2015-02-04 17:23:00+00,2015-02-04 17:46:00+00,72,W 52 St & 11 Ave,40.767272,18242,369,Washington Pl & 6 Ave,40.732241,-74.000264,19059,Subscriber,1969.0,1
11,NaN,-73.993929,NaN,1366,2015-02-04 18:40:00+00,2015-02-04 19:02:00+00,72,W 52 St & 11 Ave,40.767272,19501,476,E 31 St & 3 Ave,40.743943,-73.979661,20139,Subscriber,1971.0,1
12,NaN,-73.993929,NaN,1324,2015-02-03 10:40:00+00,2015-02-03 11:02:00+00,72,W 52 St & 11 Ave,40.767272,9087,127,Barrow St & Hudson St,40.731724,-74.006744,19275,Subscriber,1974.0,1
13,NaN,-73.993929,NaN,1293,2015-02-04 10:27:00+00,2015-02-04 10:48:00+00,72,W 52 St & 11 Ave,40.767272,15205,127,Barrow St & Hudson St,40.731724,-74.006744,17034,Subscriber,1974.0,1
14,NaN,-73.993929,NaN,1242,2015-02-05 19:28:00+00,2015-02-05 19:48:00+00,72,W 52 St & 11 Ave,40.767272,29783,476,E 31 St & 3 Ave,40.743943,-73.979661,20068,Subscriber,1971.0,1
15,NaN,-73.993929,NaN,1156,2015-02-05 13:14:00+00,2015-02-05 13:33:00+00,72,W 52 St & 11 Ave,40.767272,25953,487,E 20 St & FDR Drive,40.733143,-73.975739,16336,Subscriber,1966.0,1
16,NaN,-73.993929,NaN,1127,2015-02-07 10:41:00+00,2015-02-07 10:59:00+00,72,W 52 St & 11 Ave,40.767272,40761,382,University Pl & E 14 St,40.734927,-73.992005,20239,Subscriber,1970.0,1
17,NaN,-73.993929,NaN,1109,2015-02-02 06:35:00+00,2015-02-02 06:53:00+00,72,W 52 St & 11 Ave,40.767272,6536,446,W 24 St & 7 Ave,40.744876,-73.995299,19154,Subscriber,1970.0,1
18,NaN,-73.993929,NaN,1095,2015-02-04 23:00:00+00,2015-02-04 23:19:00+00,72,W 52 St & 11 Ave,40.767272,21477,393,E 5 St & Avenue C,40.722992,-73.979955,18808,Subscriber,1955.0,1
19,NaN,-73.993929,NaN,1082,2015-02-03 19:06:00+00,2015-02-03 19:24:00+00,72,W 52 St & 11 Ave,40.767272,11676,463,9 Ave & W 16 St,40.742065,-74.004432,19721,Subscriber,1984.0,1
20,NaN,-73.993929,NaN,1074,2015-02-03 18:12:00+00,2015-02-03 18:29:00+00,72,W 52 St & 11 Ave,40.767272,11198,367,E 53 St & Lexington Ave,40.758281,-73.970694,21021,Subscriber,1964.0,1
21,NaN,-73.993929,NaN,1054,2015-02-04 11:34:00+00,2015-02-04 11:52:00+00,72,W 52 St & 11 Ave,40.767272,15525,470,W 20 St & 8 Ave,40.743453,-74.000040,15621,Subscriber,1954.0,2
22,NaN,-73.993929,NaN,1051,2015-02-02 18:13:00+00,2015-02-02 18:31:00+00,72,W 52 St & 11 Ave,40.767272,7449,367,E 53 St & Lexington Ave,40.758281,-73.970694,18199,Subscriber,1964.0,1
23,NaN,-73.993929,NaN,1046,2015-02-07 11:43:00+00,2015-02-07 12:01:00+00,72,W 52 St & 11 Ave,40.767272,41177,440,E 45 St & 3 Ave,40.752554,-73.972826,19400,Subscriber,1992.0,1
24,NaN,-73.993929,NaN,984,2015-02-06 19:30:00+00,2015-02-06 19:46:00+00,72,W 52 St & 11 Ave,40.767272,38358,463,9 Ave & W 16 St,40.742065,-74.004432,14589,Subscriber,1984.0,1
25,NaN,-73.993929,NaN,977,2015-02-06 09:15:00+00,2015-02-06 09:32:00+00,72,W 52 St & 11 Ave,40.767272,32776,212,W 16 St & The High Line,40.743349,-74.006818,21008,Subscriber,1968.0,1
26,NaN,-73.993929,NaN,971,2015-02-04 19:12:00+00,2015-02-04 19:28:00+00,72,W 52 St & 11 Ave,40.767272,19939,463,9 Ave & W 16 St,40.742065,-74.004432,20188,Subscriber,1984.0,1
27,NaN,-73.993929,NaN,962,2015-02-01 11:47:00+00,2015-02-01 12:03:00+00,72,W 52 St & 11 Ave,40.767272,1527,212,W 16 St & The High Line,40.743349,-74.006818,16524,Subscriber,1977.0,1
28,NaN,-73.993929,NaN,961,2015-02-01 08:38:00+00,2015-02-01 08:54:00+00,72,W 52 St & 11 Ave,40.767272,387,212,W 16 St & The High Line,40.743349,-74.006818,20786,Subscriber,1972.0,2
29,NaN,-73.993929,NaN,953,2015-02-06 09:16:00+00,2015-02-06 09:32:00+00,72,W 52 St & 11 Ave,40.767272,32789,212,W 16 St & The High Line,40.743349,-74.006818,18659,Subscriber,1969.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46121,NaN,-74.015756,NaN,252,2015-02-03 18:00:00+00,2015-02-03 18:04:00+00,3002,South End Ave & Liberty St,40.711512,11092,327,Vesey Pl & River Terrace,40.715338,-74.016584,15184,Subscriber,1944.0,1
46122,NaN,-74.015756,NaN,251,2015-02-05 19:04:00+00,2015-02-05 19:09:00+00,3002,South End Ave & Liberty St,40.711512,29531,2008,Little West St & 1 Pl,40.705693,-74.016777,20663,Subscriber,1980.0,1
46123,NaN,-74.015756,NaN,243,2015-02-06 07:57:00+00,2015-02-06 08:01:00+00,3002,South End Ave & Liberty St,40.711512,31692,195,Liberty St & Broadway,40.709056,-74.010434,20226,Subscriber,1985.0,1
46124,NaN,-74.015756,NaN,243,2015-02-06 07:55:00+00,2015-02-06 07:59:00+00,3002,South End Ave & Liberty St,40.711512,31673,363,West Thames St,40.708347,-74.017134,20605,Subscriber,1958.0,2
46125,NaN,-74.015756,NaN,241,2015-02-05 11:23:00+00,2015-02-05 11:27:00+00,3002,South End Ave & Liberty St,40.711512,25268,195,Liberty St & Broadway,40.709056,-74.010434,19560,Subscriber,1958.0,1
46126,NaN,-74.015756,NaN,239,2015-02-02 23:03:00+00,2015-02-02 23:07:00+00,3002,South End Ave & Liberty St,40.711512,7866,2008,Little West St & 1 Pl,40.705693,-74.016777,17442,Subscriber,1973.0,1
46127,NaN,-74.015756,NaN,234,2015-02-05 07:54:00+00,2015-02-05 07:58:00+00,3002,South End Ave & Liberty St,40.711512,22761,363,West Thames St,40.708347,-74.017134,20188,Subscriber,1958.0,2
46128,NaN,-74.015756,NaN,217,2015-02-04 19:53:00+00,2015-02-04 19:56:00+00,3002,South End Ave & Liberty St,40.711512,20373,327,Vesey Pl & River Terrace,40.715338,-74.016584,19403,Subscriber,1959.0,2
46129,NaN,-74.015756,NaN,215,2015-02-05 18:15:00+00,2015-02-05 18:19:00+00,3002,South End Ave & Liberty St,40.711512,28881,327,Vesey Pl & River Terrace,40.715338,-74.016584,17658,Subscriber,1965.0,1
46130,NaN,-74.015756,NaN,211,2015-02-07 10:45:00+00,2015-02-07 10:48:00+00,3002,South End Ave & Liberty St,40.711512,40808,327,Vesey Pl & River Terrace,40.715338,-74.016584,14950,Subscriber,1957.0,2
46131,NaN,-74.015756,NaN,208,2015-02-06 18:00:00+00,2015-02-06 18:04:00+00,3002,South End Ave & Liberty St,40.711512,37215,2008,Little West St & 1 Pl,40.705693,-74.016777,18718,Subscriber,1984.0,1
46132,NaN,-74.015756,NaN,197,2015-02-06 19:28:00+00,2015-02-06 19:32:00+00,3002,South End Ave & Liberty St,40.711512,38342,195,Liberty St & Broadway,40.709056,-74.010434,15861,Subscriber,1985.0,1
46133,NaN,-74.015756,NaN,193,2015-02-07 08:23:00+00,2015-02-07 08:26:00+00,3002,South End Ave & Liberty St,40.711512,39902,327,Vesey Pl & River Terrace,40.715338,-74.016584,15007,Subscriber,1959.0,2
46134,NaN,-74.015756,NaN,191,2015-02-03 18:16:00+00,2015-02-03 18:19:00+00,3002,South End Ave & Liberty St,40.711512,11252,327,Vesey Pl & River Terrace,40.715338,-74.016584,15171,Subscriber,1970.0,2
46135,NaN,-74.015756,NaN,181,2015-02-01 15:47:00+00,2015-02-01 15:50:00+00,3002,South End Ave & Liberty St,40.711512,3844,2008,Little West St & 1 Pl,40.705693,-74.016777,20876,Subscriber,1984.0,1
46136,NaN,-74.015756,NaN,181,2015-02-04 15:48:00+00,2015-02-04 15:51:00+00,3002,South End Ave & Liberty St,40.711512,17198,327,Vesey Pl & River Terrace,40.715338,-74.016584,21228,Subscriber,1969.0,1
46137,NaN,-74.015756,NaN,179,2015-02-07 18:44:00+00,2015-02-07 18:47:00+00,3002,South End Ave & Liberty St,40.711512,44778,327,Vesey Pl & River Terrace,40.715338,-74.016584,21366,Subscriber,1973.0,1
46138,NaN,-74.015756,NaN,170,2015-02-03 20:40:00+00,2015-02-03 20:43:00+00,3002,South End Ave & Liberty St,40.711512,12171,363,West Thames St,40.708347,-74.017134,16155,Subscriber,1979.0,1
46139,NaN,-74.015756,NaN,167,2015-02-07 18:10:00+00,2015-02-07 18:13:00+00,3002,South End Ave & Liberty St,40.711512,44488,363,West Thames St,40.708347,-74.017134,17658,Subscriber,1972.0,2
46140,NaN,-74.015756,NaN,163,2015-02-06 17:19:00+00,2015-02-06 17:22:00+00,3002,South End Ave & Liberty St,40.711512,36546,363,West Thames St,40.708347,-74.017134,18048,Subscriber,1978.0,1
46141,NaN,-74.015756,NaN,162,2015-02-07 18:55:00+00,2015-02-07 18:57:00+00,3002,South End Ave & Liberty St,40.711512,44843,363,West Thames St,40.708347,-74.017134,17658,Subscriber,1981.0,2
46142,NaN,-74.015756,NaN,151,2015-02-07 08:20:00+00,2015-02-07 08:23:00+00,3002,South End Ave & Liberty St,40.711512,39892,327,Vesey Pl & River Terrace,40.715338,-74.016584,15008,Subscriber,1961.0,1
46143,NaN,-74.015756,NaN,150,2015-02-06 09:02:00+00,2015-02-06 09:05:00+00,3002,South End Ave & Liberty St,40.711512,32618,327,Vesey Pl & River Terrace,40.715338,-74.016584,20131,Subscriber,1978.0,2
46144,NaN,-74.015756,NaN,134,2015-02-05 05:58:00+00,2015-02-05 06:00:00+00,3002,South End Ave & Liberty St,40.711512,21869,363,West Thames St,40.708347,-74.017134,20547,Subscriber,1974.0,1
46145,NaN,-74.015756,NaN,132,2015-02-05 17:37:00+00,2015-02-05 17:39:00+00,3002,South End Ave & Liberty St,40.711512,28292,363,West Thames St,40.708347,-74.017134,20663,Subscriber,1968.0,2
46146,NaN,-74.015756,NaN,118,2015-02-07 17:25:00+00,2015-02-07 17:27:00+00,3002,South End Ave & Liberty St,40.711512,44128,363,West Thames St,40.708347,-74.017134,17272,Subscriber,1982.0,1
46147,NaN,-74.015756,NaN,108,2015-02-07 12:07:00+00,2015-02-07 12:09:00+00,3002,South End Ave & Liberty St,40.711512,41340,363,West Thames St,40.708347,-74.017134,18470,Subscriber,1979.0,1
46148,NaN,-74.015756,NaN,99,2015-02-03 09:37:00+00,2015-02-03 09:39:00+00,3002,South End Ave & Liberty St,40.711512,8857,3002,South End Ave & Liberty St,40.711512,-74.015756,18107,Subscriber,1981.0,1
46149,NaN,-74.015756,NaN,85,2015-02-04 08:16:00+00,2015-02-04 08:18:00+00,3002,South End Ave & Liberty St,40.711512,13778,3002,South End Ave & Liberty St,40.711512,-74.015756,16585,Subscriber,1967.0,1
46150,NaN,-74.015756,NaN,79,2015-02-05 16:29:00+00,2015-02-05 16:30:00+00,3002,South End Ave & Liberty St,40.711512,27360,3002,South End Ave & Liberty St,40.711512,-74.015756,17061,Subscriber,1954.0,1

### 2) Only show the top/last 10 records

In [5]:
test = '''SELECT * FROM htv210.citibike_feb_2015 
ORDER BY cartodb_id 
LIMIT 10'''
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

,the_geom,start_station_longitude,the_geom_webmercator,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,cartodb_id,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,-73.994811,NaN,801,2015-02-01 00:00:00+00,2015-02-01 00:14:00+00,521,8 Ave & W 31 St,40.750450,1,423,W 54 St & 9 Ave,40.765849,-73.986905,17131,Subscriber,1978,2
1,NaN,-73.990093,NaN,379,2015-02-01 00:00:00+00,2015-02-01 00:07:00+00,497,E 17 St & Broadway,40.737050,2,504,1 Ave & E 15 St,40.732219,-73.981656,21289,Subscriber,1993,1
2,NaN,-73.973715,NaN,2474,2015-02-01 00:01:00+00,2015-02-01 00:42:00+00,281,Grand Army Plaza & Central Park S,40.764397,3,127,Barrow St & Hudson St,40.731724,-74.006744,18903,Subscriber,1969,2
3,NaN,-74.004704,NaN,818,2015-02-01 00:01:00+00,2015-02-01 00:15:00+00,2004,6 Ave & Broome St,40.724399,4,505,6 Ave & W 33 St,40.749013,-73.988484,21044,Subscriber,1985,2
4,NaN,-73.986317,NaN,544,2015-02-01 00:01:00+00,2015-02-01 00:10:00+00,323,Lawrence St & Willoughby St,40.692362,5,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,19868,Subscriber,1957,1
5,NaN,-73.953820,NaN,717,2015-02-01 00:02:00+00,2015-02-01 00:14:00+00,373,Willoughby Ave & Walworth St,40.693317,6,2002,Wythe Ave & Metropolitan Ave,40.716887,-73.963198,15854,Subscriber,1979,1
6,NaN,-73.977225,NaN,1306,2015-02-01 00:04:00+00,2015-02-01 00:26:00+00,352,W 56 St & 6 Ave,40.763406,7,504,1 Ave & E 15 St,40.732219,-73.981656,15173,Subscriber,1983,1
7,NaN,-73.989780,NaN,913,2015-02-01 00:04:00+00,2015-02-01 00:19:00+00,439,E 4 St & 2 Ave,40.726281,8,116,W 17 St & 8 Ave,40.741776,-74.001497,17862,Subscriber,1955,1
8,NaN,-73.994046,NaN,759,2015-02-01 00:04:00+00,2015-02-01 00:17:00+00,335,Washington Pl & Broadway,40.729039,9,2012,E 27 St & 1 Ave,40.739445,-73.976806,21183,Subscriber,1985,2
9,NaN,-74.002638,NaN,585,2015-02-01 00:05:00+00,2015-02-01 00:15:00+00,284,Greenwich Ave & 8 Ave,40.739017,10,444,Broadway & W 24 St,40.742354,-73.989151,14843,Subscriber,1982,1

In [6]:
test = '''SELECT * FROM htv210.citibike_feb_2015 
ORDER BY cartodb_id DESC 
LIMIT 10'''
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

,the_geom,start_station_longitude,the_geom_webmercator,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,cartodb_id,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,-73.989780,NaN,917,2015-02-07 23:59:00+00,2015-02-08 00:15:00+00,439,E 4 St & 2 Ave,40.726281,46200,417,Barclay St & Church St,40.712912,-74.010202,20998,Subscriber,1965,2
1,NaN,-74.002150,NaN,548,2015-02-07 23:58:00+00,2015-02-08 00:08:00+00,368,Carmine St & 6 Ave,40.730386,46199,334,W 20 St & 7 Ave,40.742388,-73.997262,19540,Subscriber,1983,2
2,NaN,-73.986831,NaN,392,2015-02-07 23:57:00+00,2015-02-08 00:03:00+00,474,5 Ave & E 29 St,40.745168,46198,325,E 19 St & 3 Ave,40.736245,-73.984738,15545,Subscriber,1986,1
3,NaN,-73.986831,NaN,428,2015-02-07 23:57:00+00,2015-02-08 00:04:00+00,474,5 Ave & E 29 St,40.745168,46197,325,E 19 St & 3 Ave,40.736245,-73.984738,16395,Subscriber,1986,2
4,NaN,-74.000040,NaN,689,2015-02-07 23:57:00+00,2015-02-08 00:08:00+00,470,W 20 St & 8 Ave,40.743453,46196,325,E 19 St & 3 Ave,40.736245,-73.984738,15585,Subscriber,1953,1
5,NaN,-73.969053,NaN,1422,2015-02-07 23:57:00+00,2015-02-08 00:20:00+00,455,1 Ave & E 44 St,40.750020,46195,265,Stanton St & Chrystie St,40.722293,-73.991475,20184,Subscriber,1960,2
6,NaN,-73.982050,NaN,993,2015-02-07 23:56:00+00,2015-02-08 00:13:00+00,461,E 20 St & 2 Ave,40.735877,46194,295,Pike St & E Broadway,40.714067,-73.992939,16722,Subscriber,1974,1
7,NaN,-74.009106,NaN,1165,2015-02-07 23:56:00+00,2015-02-08 00:15:00+00,152,Warren St & Church St,40.714740,46193,325,E 19 St & 3 Ave,40.736245,-73.984738,16978,Subscriber,1959,1
8,NaN,-73.993012,NaN,1248,2015-02-07 23:56:00+00,2015-02-08 00:17:00+00,495,W 47 St & 10 Ave,40.762699,46192,432,E 7 St & Avenue A,40.726218,-73.983799,16300,Subscriber,1984,1
9,NaN,-74.001497,NaN,306,2015-02-07 23:55:00+00,2015-02-08 00:01:00+00,116,W 17 St & 8 Ave,40.741776,46191,494,W 26 St & 8 Ave,40.747348,-73.997236,14736,Subscriber,1983,2

### 3) List all unique start_station_id values

In [7]:
test = '''SELECT DISTINCT start_station_id FROM htv210.citibike_feb_2015'''
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

     start_station_id  Unnamed: 1
0                 120         NaN
1                 285         NaN
2                 251         NaN
3                 195         NaN
4                 453         NaN
5                 144         NaN
6                 266         NaN
7                 263         NaN
8                 216         NaN
9                 328         NaN
10                353         NaN
11                212         NaN
12                383         NaN
13                538         NaN
14                217         NaN
15                300         NaN
16                456         NaN
17                128         NaN
18                223         NaN
19                244         NaN
20                494         NaN
21                403         NaN
22                260         NaN
23                411         NaN
24                445         NaN
25                377         NaN
26                427         NaN
27                232         NaN
28                331         NaN
29                416         NaN
..                ...         ...
297               127         NaN
298               397         NaN
299               454         NaN
300               310         NaN
301               531         NaN
302               268         NaN
303               329         NaN
304               518         NaN
305               514         NaN
306               437         NaN
307               270         NaN
308               356         NaN
309               399         NaN
310               119         NaN
311               384         NaN
312               151         NaN
313               362         NaN
314               262         NaN
315               313         NaN
316              2008         NaN
317               276         NaN
318               470         NaN
319               455         NaN
320               496         NaN
321               312         NaN
322               318         NaN
323               305         NaN
324               497         NaN
325               264         NaN
326               483         NaN

[327 rows x 2 columns]

### 4) Aggregation functions:

In [8]:
test = '''SELECT COUNT(cartodb_id) FROM htv210.citibike_feb_2015'''
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

   count  Unnamed: 1
0  46200         NaN

In [9]:
test = '''SELECT AVG(tripduration) AS Average, 
MIN(tripduration) AS Minimum, 
MAX(tripduration) AS Maximum FROM htv210.citibike_feb_2015'''
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

      average  minimum  maximum
0  675.865823       60    43016

## Task 2
### 1) Selecting trips started on Feb-02-2015 only

In [10]:
test = '''SELECT * FROM htv210.citibike_feb_2015 
WHERE EXTRACT(DAY FROM starttime::date) = 2'''
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

,the_geom,start_station_longitude,the_geom_webmercator,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,cartodb_id,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,-73.979955,NaN,1312,2015-02-02 11:07:00+00,2015-02-02 11:29:00+00,393,E 5 St & Avenue C,40.722992,6920,476,E 31 St & 3 Ave,40.743943,-73.979661,17720,Subscriber,1955.0,1
1,NaN,-74.004432,NaN,444,2015-02-02 00:40:00+00,2015-02-02 00:48:00+00,463,9 Ave & W 16 St,40.742065,6477,489,10 Ave & W 28 St,40.750664,-74.001768,20233,Subscriber,1971.0,1
2,NaN,-74.004432,NaN,438,2015-02-02 00:40:00+00,2015-02-02 00:47:00+00,463,9 Ave & W 16 St,40.742065,6478,489,10 Ave & W 28 St,40.750664,-74.001768,20264,Subscriber,1981.0,2
3,NaN,-73.990931,NaN,498,2015-02-02 06:20:00+00,2015-02-02 06:28:00+00,492,W 33 St & 7 Ave,40.750200,6526,493,W 45 St & 6 Ave,40.756800,-73.982912,16013,Subscriber,1962.0,2
4,NaN,-73.993915,NaN,199,2015-02-02 00:02:00+00,2015-02-02 00:05:00+00,442,W 27 St & 7 Ave,40.746647,6442,489,10 Ave & W 28 St,40.750664,-74.001768,20684,Subscriber,1992.0,1
5,NaN,-73.984267,NaN,418,2015-02-02 00:03:00+00,2015-02-02 00:10:00+00,326,E 11 St & 1 Ave,40.729538,6443,349,Rivington St & Ridge St,40.718502,-73.983299,16094,Subscriber,1964.0,2
6,NaN,-74.001670,NaN,276,2015-02-02 00:04:00+00,2015-02-02 00:09:00+00,279,Peck Slip & Front St,40.707873,6444,415,Pearl St & Hanover Square,40.704718,-74.009260,17362,Subscriber,1974.0,1
7,NaN,-73.992390,NaN,420,2015-02-02 00:06:00+00,2015-02-02 00:13:00+00,496,E 16 St & 5 Ave,40.737262,6445,237,E 11 St & 2 Ave,40.730473,-73.986724,15475,Subscriber,1992.0,2
8,NaN,-73.990026,NaN,304,2015-02-02 00:07:00+00,2015-02-02 00:12:00+00,477,W 41 St & 8 Ave,40.756405,6446,450,W 49 St & 8 Ave,40.762272,-73.987882,16272,Subscriber,1968.0,1
9,NaN,-73.978951,NaN,622,2015-02-02 00:08:00+00,2015-02-02 00:18:00+00,467,Dean St & 4 Ave,40.683125,6447,391,Clark St & Henry St,40.697601,-73.993446,16370,Subscriber,1979.0,1
10,NaN,-74.003664,NaN,371,2015-02-02 00:09:00+00,2015-02-02 00:15:00+00,434,9 Ave & W 18 St,40.743174,6448,482,W 15 St & 7 Ave,40.739355,-73.999318,19437,Subscriber,1963.0,1
11,NaN,-74.005628,NaN,477,2015-02-02 00:11:00+00,2015-02-02 00:19:00+00,330,Reade St & Broadway,40.714505,6449,2008,Little West St & 1 Pl,40.705693,-74.016777,21211,Subscriber,1982.0,1
12,NaN,-73.994811,NaN,743,2015-02-02 00:12:00+00,2015-02-02 00:25:00+00,521,8 Ave & W 31 St,40.750450,6450,423,W 54 St & 9 Ave,40.765849,-73.986905,21417,Subscriber,1978.0,2
13,NaN,-73.981656,NaN,599,2015-02-02 00:12:00+00,2015-02-02 00:22:00+00,504,1 Ave & E 15 St,40.732219,6451,453,W 22 St & 8 Ave,40.744751,-73.999154,15722,Subscriber,1956.0,1
14,NaN,-73.990741,NaN,345,2015-02-02 00:12:00+00,2015-02-02 00:18:00+00,285,Broadway & E 14 St,40.734546,6452,236,St Marks Pl & 2 Ave,40.728419,-73.987140,18972,Subscriber,1962.0,1
15,NaN,-73.983688,NaN,721,2015-02-02 00:13:00+00,2015-02-02 00:25:00+00,301,E 2 St & Avenue B,40.722174,6453,476,E 31 St & 3 Ave,40.743943,-73.979661,19628,Subscriber,1980.0,1
16,NaN,-74.001670,NaN,182,2015-02-02 00:13:00+00,2015-02-02 00:16:00+00,279,Peck Slip & Front St,40.707873,6454,376,John St & William St,40.708621,-74.007222,15169,Subscriber,1978.0,1
17,NaN,-73.980166,NaN,154,2015-02-02 00:13:00+00,2015-02-02 00:16:00+00,342,Columbia St & Rivington St,40.717400,6455,411,E 6 St & Avenue D,40.722281,-73.976687,17533,Subscriber,1997.0,1
18,NaN,-74.000040,NaN,435,2015-02-02 00:14:00+00,2015-02-02 00:21:00+00,470,W 20 St & 8 Ave,40.743453,6456,491,E 24 St & Park Ave S,40.740964,-73.986022,19761,Subscriber,1983.0,1
19,NaN,-73.987140,NaN,310,2015-02-02 00:15:00+00,2015-02-02 00:20:00+00,236,St Marks Pl & 2 Ave,40.728419,6457,393,E 5 St & Avenue C,40.722992,-73.979955,17267,Subscriber,1993.0,1
20,NaN,-74.000040,NaN,1274,2015-02-02 00:16:00+00,2015-02-02 00:37:00+00,470,W 20 St & 8 Ave,40.743453,6458,470,W 20 St & 8 Ave,40.743453,-74.000040,18691,Subscriber,1964.0,1
21,NaN,-73.983390,NaN,642,2015-02-02 00:18:00+00,2015-02-02 00:29:00+00,485,W 37 St & 5 Ave,40.750380,6459,174,E 25 St & 1 Ave,40.738177,-73.977387,17106,Subscriber,1977.0,1
22,NaN,-73.997044,NaN,256,2015-02-02 00:18:00+00,2015-02-02 00:22:00+00,345,W 13 St & 6 Ave,40.736494,6460,483,E 12 St & 3 Ave,40.732233,-73.988900,20009,Subscriber,1973.0,1
23,NaN,-74.001768,NaN,334,2015-02-02 00:19:00+00,2015-02-02 00:25:00+00,489,10 Ave & W 28 St,40.750664,6461,442,W 27 St & 7 Ave,40.746647,-73.993915,18777,Subscriber,1979.0,1
24,NaN,-73.979738,NaN,90,2015-02-02 00:19:00+00,2015-02-02 00:20:00+00,507,E 25 St & 2 Ave,40.739126,6462,174,E 25 St & 1 Ave,40.738177,-73.977387,15357,Subscriber,1989.0,1
25,NaN,-74.002939,NaN,203,2015-02-02 00:20:00+00,2015-02-02 00:23:00+00,380,W 4 St & 7 Ave S,40.734011,6463,405,Washington St & Gansevoort St,40.739323,-74.008119,18487,Subscriber,1983.0,1
26,NaN,-73.997262,NaN,649,2015-02-02 00:22:00+00,2015-02-02 00:32:00+00,334,W 20 St & 7 Ave,40.742388,6464,439,E 4 St & 2 Ave,40.726281,-73.989780,20863,Subscriber,1981.0,1
27,NaN,-73.996674,NaN,319,2015-02-02 00:23:00+00,2015-02-02 00:29:00+00,508,W 46 St & 11 Ave,40.763414,6465,448,W 37 St & 10 Ave,40.756604,-73.997901,16539,Subscriber,1970.0,1
28,NaN,-73.987834,NaN,154,2015-02-02 00:27:00+00,2015-02-02 00:30:00+00,428,E 3 St & 1 Ave,40.724677,6466,301,E 2 St & Avenue B,40.722174,-73.983688,18737,Subscriber,1961.0,1
29,NaN,-73.991930,NaN,550,2015-02-02 00:28:00+00,2015-02-02 00:37:00+00,331,Pike St & Monroe St,40.711731,6467,195,Liberty St & Broadway,40.709056,-74.010434,17797,Subscriber,1980.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429,NaN,-73.989111,NaN,722,2015-02-02 23:08:00+00,2015-02-02 23:20:00+00,312,Allen St & E Houston St,40.722055,7871,380,W 4 St & 7 Ave S,40.734011,-74.002939,20572,Subscriber,1985.0,1
1430,NaN,-73.988557,NaN,274,2015-02-02 23:08:00+00,2015-02-02 23:12:00+00,486,Broadway & W 29 St,40.746201,7872,491,E 24 St & Park Ave S,40.740964,-73.986022,20338,Subscriber,1981.0,1
1431,NaN,-73.977225,NaN,951,2015-02-02 23:11:00+00,2015-02-02 23:27:00+00,352,W 56 St & 6 Ave,40.763406,7873,515,W 43 St & 10 Ave,40.760094,-73.994618,15826,Subscriber,1978.0,1
1432,NaN,-74.001768,NaN,276,2015-02-02 23:16:00+00,2015-02-02 23:20:00+00,489,10 Ave & W 28 St,40.750664,7874,521,8 Ave & W 31 St,40.750450,-73.994811,18325,Subscriber,1990.0,1
1433,NaN,-73.997236,NaN,426,2015-02-02 23:17:00+00,2015-02-02 23:24:00+00,494,W 26 St & 8 Ave,40.747348,7875,434,9 Ave & W 18 St,40.743174,-74.003664,16654,Subscriber,1977.0,1
1434,NaN,-73.989551,NaN,578,2015-02-02 23:19:00+00,2015-02-02 23:28:00+00,402,Broadway & E 22 St,40.740343,7876,229,Great Jones St,40.727434,-73.993790,20902,Subscriber,1966.0,1
1435,NaN,-73.970325,NaN,2621,2015-02-02 23:22:00+00,2015-02-03 00:06:00+00,164,E 47 St & 2 Ave,40.753231,7877,2017,E 43 St & 2 Ave,40.750224,-73.971214,20796,Subscriber,1954.0,1
1436,NaN,-73.988084,NaN,621,2015-02-02 23:22:00+00,2015-02-02 23:32:00+00,498,Broadway & W 32 St,40.748549,7878,449,W 52 St & 9 Ave,40.764618,-73.987895,20160,Subscriber,1989.0,1
1437,NaN,-73.994811,NaN,323,2015-02-02 23:23:00+00,2015-02-02 23:29:00+00,521,8 Ave & W 31 St,40.750450,7879,477,W 41 St & 8 Ave,40.756405,-73.990026,17392,Subscriber,1974.0,1
1438,NaN,-74.003664,NaN,393,2015-02-02 23:24:00+00,2015-02-02 23:31:00+00,434,9 Ave & W 18 St,40.743174,7880,482,W 15 St & 7 Ave,40.739355,-73.999318,17263,Subscriber,1963.0,1
1439,NaN,-73.998102,NaN,597,2015-02-02 23:25:00+00,2015-02-02 23:35:00+00,161,LaGuardia Pl & W 3 St,40.729170,7881,497,E 17 St & Broadway,40.737050,-73.990093,19858,Subscriber,1955.0,1
1440,NaN,-73.997236,NaN,244,2015-02-02 23:25:00+00,2015-02-02 23:30:00+00,494,W 26 St & 8 Ave,40.747348,7882,462,W 22 St & 10 Ave,40.746920,-74.004519,20319,Subscriber,1979.0,1
1441,NaN,-74.005301,NaN,1023,2015-02-02 23:26:00+00,2015-02-02 23:43:00+00,306,Cliff St & Fulton St,40.708235,7883,127,Barrow St & Hudson St,40.731724,-74.006744,21600,Subscriber,1977.0,1
1442,NaN,-73.983299,NaN,419,2015-02-02 23:31:00+00,2015-02-02 23:38:00+00,349,Rivington St & Ridge St,40.718502,7884,473,Rivington St & Chrystie St,40.721101,-73.991925,18791,Subscriber,1986.0,1
1443,NaN,-73.987882,NaN,1429,2015-02-02 23:32:00+00,2015-02-02 23:55:00+00,450,W 49 St & 8 Ave,40.762272,7885,358,Christopher St & Greenwich St,40.732916,-74.007114,17730,Subscriber,1966.0,1
1444,NaN,-73.977706,NaN,676,2015-02-02 23:32:00+00,2015-02-02 23:44:00+00,519,Pershing Square North,40.751873,7886,477,W 41 St & 8 Ave,40.756405,-73.990026,18147,Subscriber,1980.0,1
1445,NaN,-73.983035,NaN,879,2015-02-02 23:33:00+00,2015-02-02 23:48:00+00,546,E 30 St & Park Ave S,40.744449,7887,489,10 Ave & W 28 St,40.750664,-74.001768,20249,Subscriber,1959.0,1
1446,NaN,-73.999061,NaN,593,2015-02-02 23:35:00+00,2015-02-02 23:45:00+00,336,Sullivan St & Washington Sq,40.730477,7888,432,E 7 St & Avenue A,40.726218,-73.983799,18078,Subscriber,1988.0,1
1447,NaN,-73.990985,NaN,839,2015-02-02 23:36:00+00,2015-02-02 23:50:00+00,529,W 42 St & 8 Ave,40.757570,7889,164,E 47 St & 2 Ave,40.753231,-73.970325,16808,Subscriber,1983.0,1
1448,NaN,-73.989551,NaN,560,2015-02-02 23:37:00+00,2015-02-02 23:46:00+00,402,Broadway & E 22 St,40.740343,7890,368,Carmine St & 6 Ave,40.730386,-74.002150,21355,Subscriber,1986.0,1
1449,NaN,-73.981656,NaN,165,2015-02-02 23:37:00+00,2015-02-02 23:40:00+00,504,1 Ave & E 15 St,40.732219,7891,511,E 14 St & Avenue B,40.729387,-73.977724,15359,Subscriber,1994.0,1
1450,NaN,-73.988484,NaN,813,2015-02-02 23:42:00+00,2015-02-02 23:56:00+00,505,6 Ave & W 33 St,40.749013,7892,489,10 Ave & W 28 St,40.750664,-74.001768,18250,Subscriber,1982.0,2
1451,NaN,-74.001971,NaN,764,2015-02-02 23:42:00+00,2015-02-02 23:55:00+00,509,9 Ave & W 22 St,40.745497,7893,507,E 25 St & 2 Ave,40.739126,-73.979738,16969,Subscriber,1987.0,1
1452,NaN,-73.992390,NaN,2111,2015-02-02 23:43:00+00,2015-02-03 00:18:00+00,496,E 16 St & 5 Ave,40.737262,7894,397,Fulton St & Clermont Ave,40.684157,-73.969223,18825,Subscriber,1979.0,1
1453,NaN,-73.995101,NaN,518,2015-02-02 23:43:00+00,2015-02-02 23:52:00+00,280,E 10 St & 5 Ave,40.733320,7895,439,E 4 St & 2 Ave,40.726281,-73.989780,19000,Subscriber,1983.0,1
1454,NaN,-73.980144,NaN,371,2015-02-02 23:45:00+00,2015-02-02 23:52:00+00,484,W 44 St & 5 Ave,40.755003,7896,440,E 45 St & 3 Ave,40.752554,-73.972826,20723,Subscriber,1977.0,1
1455,NaN,-74.005524,NaN,188,2015-02-02 23:47:00+00,2015-02-02 23:50:00+00,224,Spruce St & Nassau St,40.711464,7897,417,Barclay St & Church St,40.712912,-74.010202,16528,Subscriber,1988.0,1
1456,NaN,-73.997044,NaN,689,2015-02-02 23:50:00+00,2015-02-03 00:02:00+00,345,W 13 St & 6 Ave,40.736494,7898,394,E 9 St & Avenue C,40.725213,-73.977688,16541,Subscriber,1988.0,1
1457,NaN,-73.999154,NaN,634,2015-02-02 23:55:00+00,2015-02-03 00:05:00+00,453,W 22 St & 8 Ave,40.744751,7899,537,Lexington Ave & E 24 St,40.740259,-73.984092,14878,Subscriber,1961.0,1
1458,NaN,-73.990741,NaN,733,2015-02-02 23:58:00+00,2015-02-03 00:10:00+00,285,Broadway & E 14 St,40.734546,7900,302,Avenue D & E 3 St,40.720828,-73.977932,16326,Subscriber,1976.0,2

### 2) Selecting trips started on the weekends

In [11]:
test = '''SELECT * FROM htv210.citibike_feb_2015 
WHERE EXTRACT(DAY FROM starttime::date) IN (1,7)
ORDER BY starttime'''
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

,the_geom,start_station_longitude,the_geom_webmercator,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,cartodb_id,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,-73.990093,NaN,379,2015-02-01 00:00:00+00,2015-02-01 00:07:00+00,497,E 17 St & Broadway,40.737050,2,504,1 Ave & E 15 St,40.732219,-73.981656,21289,Subscriber,1993.0,1
1,NaN,-73.994811,NaN,801,2015-02-01 00:00:00+00,2015-02-01 00:14:00+00,521,8 Ave & W 31 St,40.750450,1,423,W 54 St & 9 Ave,40.765849,-73.986905,17131,Subscriber,1978.0,2
2,NaN,-73.973715,NaN,2474,2015-02-01 00:01:00+00,2015-02-01 00:42:00+00,281,Grand Army Plaza & Central Park S,40.764397,3,127,Barrow St & Hudson St,40.731724,-74.006744,18903,Subscriber,1969.0,2
3,NaN,-73.986317,NaN,544,2015-02-01 00:01:00+00,2015-02-01 00:10:00+00,323,Lawrence St & Willoughby St,40.692362,5,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,19868,Subscriber,1957.0,1
4,NaN,-74.004704,NaN,818,2015-02-01 00:01:00+00,2015-02-01 00:15:00+00,2004,6 Ave & Broome St,40.724399,4,505,6 Ave & W 33 St,40.749013,-73.988484,21044,Subscriber,1985.0,2
5,NaN,-73.953820,NaN,717,2015-02-01 00:02:00+00,2015-02-01 00:14:00+00,373,Willoughby Ave & Walworth St,40.693317,6,2002,Wythe Ave & Metropolitan Ave,40.716887,-73.963198,15854,Subscriber,1979.0,1
6,NaN,-73.977225,NaN,1306,2015-02-01 00:04:00+00,2015-02-01 00:26:00+00,352,W 56 St & 6 Ave,40.763406,7,504,1 Ave & E 15 St,40.732219,-73.981656,15173,Subscriber,1983.0,1
7,NaN,-73.994046,NaN,759,2015-02-01 00:04:00+00,2015-02-01 00:17:00+00,335,Washington Pl & Broadway,40.729039,9,2012,E 27 St & 1 Ave,40.739445,-73.976806,21183,Subscriber,1985.0,2
8,NaN,-73.989780,NaN,913,2015-02-01 00:04:00+00,2015-02-01 00:19:00+00,439,E 4 St & 2 Ave,40.726281,8,116,W 17 St & 8 Ave,40.741776,-74.001497,17862,Subscriber,1955.0,1
9,NaN,-74.002638,NaN,585,2015-02-01 00:05:00+00,2015-02-01 00:15:00+00,284,Greenwich Ave & 8 Ave,40.739017,10,444,Broadway & W 24 St,40.742354,-73.989151,14843,Subscriber,1982.0,1
10,NaN,-73.988084,NaN,204,2015-02-01 00:05:00+00,2015-02-01 00:08:00+00,498,Broadway & W 32 St,40.748549,12,472,E 32 St & Park Ave,40.745712,-73.981948,21507,Subscriber,1991.0,2
11,NaN,-74.002638,NaN,581,2015-02-01 00:05:00+00,2015-02-01 00:15:00+00,284,Greenwich Ave & 8 Ave,40.739017,11,444,Broadway & W 24 St,40.742354,-73.989151,16936,Subscriber,1988.0,2
12,NaN,-74.002150,NaN,1169,2015-02-01 00:07:00+00,2015-02-01 00:27:00+00,368,Carmine St & 6 Ave,40.730386,13,307,Canal St & Rutgers St,40.714275,-73.989900,17456,Subscriber,1982.0,2
13,NaN,-73.984267,NaN,419,2015-02-01 00:07:00+00,2015-02-01 00:14:00+00,326,E 11 St & 1 Ave,40.729538,14,2012,E 27 St & 1 Ave,40.739445,-73.976806,14679,Subscriber,1990.0,2
14,NaN,-73.990741,NaN,527,2015-02-01 00:09:00+00,2015-02-01 00:17:00+00,285,Broadway & E 14 St,40.734546,15,212,W 16 St & The High Line,40.743349,-74.006818,18978,Subscriber,1977.0,1
15,NaN,-74.002150,NaN,1013,2015-02-01 00:10:00+00,2015-02-01 00:27:00+00,368,Carmine St & 6 Ave,40.730386,16,488,W 39 St & 9 Ave,40.756458,-73.993722,16496,Subscriber,1968.0,1
16,NaN,-73.984267,NaN,525,2015-02-01 00:13:00+00,2015-02-01 00:22:00+00,326,E 11 St & 1 Ave,40.729538,18,507,E 25 St & 2 Ave,40.739126,-73.979738,16984,Subscriber,1987.0,1
17,NaN,-73.977688,NaN,587,2015-02-01 00:13:00+00,2015-02-01 00:23:00+00,394,E 9 St & Avenue C,40.725213,17,331,Pike St & Monroe St,40.711731,-73.991930,17107,Subscriber,1990.0,1
18,NaN,-73.982912,NaN,670,2015-02-01 00:14:00+00,2015-02-01 00:26:00+00,493,W 45 St & 6 Ave,40.756800,19,305,E 58 St & 3 Ave,40.760958,-73.967245,15997,Subscriber,1980.0,1
19,NaN,-73.981420,NaN,711,2015-02-01 00:15:00+00,2015-02-01 00:27:00+00,445,E 10 St & Avenue A,40.727408,20,223,W 13 St & 7 Ave,40.737815,-73.999947,21516,Subscriber,1960.0,1
20,NaN,-73.987834,NaN,1559,2015-02-01 00:16:00+00,2015-02-01 00:42:00+00,428,E 3 St & 1 Ave,40.724677,21,457,Broadway & W 58 St,40.766953,-73.981693,15815,Subscriber,1986.0,1
21,NaN,-73.971879,NaN,683,2015-02-01 00:16:00+00,2015-02-01 00:27:00+00,228,E 48 St & 3 Ave,40.754601,22,477,W 41 St & 8 Ave,40.756405,-73.990026,18727,Subscriber,1987.0,1
22,NaN,-73.988639,NaN,522,2015-02-01 00:16:00+00,2015-02-01 00:24:00+00,513,W 56 St & 10 Ave,40.768254,23,488,W 39 St & 9 Ave,40.756458,-73.993722,14982,Subscriber,1969.0,1
23,NaN,-73.979738,NaN,389,2015-02-01 00:16:00+00,2015-02-01 00:23:00+00,507,E 25 St & 2 Ave,40.739126,24,518,E 39 St & 2 Ave,40.747804,-73.973442,16391,Subscriber,1957.0,1
24,NaN,-73.989780,NaN,276,2015-02-01 00:16:00+00,2015-02-01 00:21:00+00,439,E 4 St & 2 Ave,40.726281,25,473,Rivington St & Chrystie St,40.721101,-73.991925,15947,Subscriber,1981.0,1
25,NaN,-74.002971,NaN,907,2015-02-01 00:17:00+00,2015-02-01 00:32:00+00,128,MacDougal St & Prince St,40.727103,26,531,Forsyth St & Broome St,40.718939,-73.992663,16917,Subscriber,1993.0,1
26,NaN,-73.993934,NaN,946,2015-02-01 00:18:00+00,2015-02-01 00:33:00+00,490,8 Ave & W 33 St,40.751551,27,528,2 Ave & E 31 St,40.742909,-73.977061,15924,Subscriber,1975.0,1
27,NaN,-73.987030,NaN,144,2015-02-01 00:18:00+00,2015-02-01 00:21:00+00,350,Clinton St & Grand St,40.715595,28,502,Henry St & Grand St,40.714215,-73.981346,21321,Subscriber,1973.0,1
28,NaN,-73.995653,NaN,257,2015-02-01 00:19:00+00,2015-02-01 00:23:00+00,250,Lafayette St & Jersey St,40.724561,29,401,Allen St & Rivington St,40.720196,-73.989978,16861,Subscriber,1973.0,2
29,NaN,-73.981656,NaN,602,2015-02-01 00:20:00+00,2015-02-01 00:30:00+00,504,1 Ave & E 15 St,40.732219,30,411,E 6 St & Avenue D,40.722281,-73.976687,21289,Subscriber,1977.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13201,NaN,-73.994046,NaN,812,2015-02-07 23:51:00+00,2015-02-08 00:05:00+00,335,Washington Pl & Broadway,40.729039,46171,435,W 21 St & 6 Ave,40.741740,-73.994156,15733,Subscriber,1988.0,1
13202,NaN,-73.991908,NaN,647,2015-02-07 23:51:00+00,2015-02-08 00:02:00+00,361,Allen St & Hester St,40.716059,46172,504,1 Ave & E 15 St,40.732219,-73.981656,16931,Subscriber,1995.0,1
13203,NaN,-74.009106,NaN,563,2015-02-07 23:51:00+00,2015-02-08 00:00:00+00,152,Warren St & Church St,40.714740,46173,401,Allen St & Rivington St,40.720196,-73.989978,17202,Subscriber,1987.0,1
13204,NaN,-73.988900,NaN,470,2015-02-07 23:51:00+00,2015-02-07 23:59:00+00,483,E 12 St & 3 Ave,40.732233,46174,439,E 4 St & 2 Ave,40.726281,-73.989780,20314,Subscriber,1989.0,2
13205,NaN,-73.978951,NaN,299,2015-02-07 23:51:00+00,2015-02-07 23:56:00+00,467,Dean St & 4 Ave,40.683125,46175,395,Bond St & Schermerhorn St,40.688070,-73.984106,21531,Subscriber,1989.0,1
13206,NaN,-73.991908,NaN,629,2015-02-07 23:52:00+00,2015-02-08 00:02:00+00,361,Allen St & Hester St,40.716059,46176,504,1 Ave & E 15 St,40.732219,-73.981656,21491,Subscriber,1968.0,1
13207,NaN,-73.989551,NaN,499,2015-02-07 23:52:00+00,2015-02-08 00:00:00+00,402,Broadway & E 22 St,40.740343,46177,380,W 4 St & 7 Ave S,40.734011,-74.002939,15367,Subscriber,1990.0,1
13208,NaN,-74.000264,NaN,474,2015-02-07 23:52:00+00,2015-02-08 00:00:00+00,369,Washington Pl & 6 Ave,40.732241,46178,368,Carmine St & 6 Ave,40.730386,-74.002150,18978,Subscriber,1973.0,2
13209,NaN,-73.979661,NaN,345,2015-02-07 23:52:00+00,2015-02-07 23:58:00+00,476,E 31 St & 3 Ave,40.743943,46179,504,1 Ave & E 15 St,40.732219,-73.981656,19507,Subscriber,1980.0,1
13210,NaN,-74.002150,NaN,776,2015-02-07 23:53:00+00,2015-02-08 00:05:00+00,368,Carmine St & 6 Ave,40.730386,46181,531,Forsyth St & Broome St,40.718939,-73.992663,18689,Subscriber,1982.0,1
13211,NaN,-73.981918,NaN,829,2015-02-07 23:53:00+00,2015-02-08 00:07:00+00,499,Broadway & W 60 St,40.769155,46180,160,E 37 St & Lexington Ave,40.748238,-73.978311,16936,Subscriber,1980.0,1
13212,NaN,-73.976485,NaN,697,2015-02-07 23:53:00+00,2015-02-08 00:05:00+00,520,W 52 St & 5 Ave,40.759923,46182,478,11 Ave & W 41 St,40.760301,-73.998842,15781,Subscriber,1972.0,1
13213,NaN,-73.978951,NaN,1703,2015-02-07 23:54:00+00,2015-02-08 00:23:00+00,467,Dean St & 4 Ave,40.683125,46183,471,Grand St & Havemeyer St,40.712868,-73.956981,15081,Subscriber,1988.0,1
13214,NaN,-73.991255,NaN,922,2015-02-07 23:54:00+00,2015-02-08 00:10:00+00,479,9 Ave & W 45 St,40.760193,46184,247,Perry St & Bleecker St,40.735354,-74.004831,21672,Subscriber,1983.0,1
13215,NaN,-73.981693,NaN,849,2015-02-07 23:54:00+00,2015-02-08 00:08:00+00,457,Broadway & W 58 St,40.766953,46185,488,W 39 St & 9 Ave,40.756458,-73.993722,16336,Subscriber,1970.0,1
13216,NaN,-73.981693,NaN,826,2015-02-07 23:54:00+00,2015-02-08 00:08:00+00,457,Broadway & W 58 St,40.766953,46186,488,W 39 St & 9 Ave,40.756458,-73.993722,21609,Subscriber,1973.0,1
13217,NaN,-74.009660,NaN,473,2015-02-07 23:54:00+00,2015-02-08 00:02:00+00,328,Watts St & Greenwich St,40.724055,46187,3002,South End Ave & Liberty St,40.711512,-74.015756,19470,Subscriber,1964.0,1
13218,NaN,-73.980420,NaN,332,2015-02-07 23:54:00+00,2015-02-07 23:59:00+00,510,W 51 St & 6 Ave,40.760660,46188,450,W 49 St & 8 Ave,40.762272,-73.987882,18167,Subscriber,1960.0,1
13219,NaN,-73.998004,NaN,327,2015-02-07 23:55:00+00,2015-02-08 00:01:00+00,254,W 11 St & 6 Ave,40.735324,46190,466,W 25 St & 6 Ave,40.743954,-73.991449,17541,Subscriber,1983.0,1
13220,NaN,-73.992005,NaN,456,2015-02-07 23:55:00+00,2015-02-08 00:03:00+00,382,University Pl & E 14 St,40.734927,46189,404,9 Ave & W 14 St,40.740583,-74.005509,15929,Subscriber,1987.0,1
13221,NaN,-74.001497,NaN,306,2015-02-07 23:55:00+00,2015-02-08 00:01:00+00,116,W 17 St & 8 Ave,40.741776,46191,494,W 26 St & 8 Ave,40.747348,-73.997236,14736,Subscriber,1983.0,2
13222,NaN,-74.009106,NaN,1165,2015-02-07 23:56:00+00,2015-02-08 00:15:00+00,152,Warren St & Church St,40.714740,46193,325,E 19 St & 3 Ave,40.736245,-73.984738,16978,Subscriber,1959.0,1
13223,NaN,-73.993012,NaN,1248,2015-02-07 23:56:00+00,2015-02-08 00:17:00+00,495,W 47 St & 10 Ave,40.762699,46192,432,E 7 St & Avenue A,40.726218,-73.983799,16300,Subscriber,1984.0,1
13224,NaN,-73.982050,NaN,993,2015-02-07 23:56:00+00,2015-02-08 00:13:00+00,461,E 20 St & 2 Ave,40.735877,46194,295,Pike St & E Broadway,40.714067,-73.992939,16722,Subscriber,1974.0,1
13225,NaN,-74.000040,NaN,689,2015-02-07 23:57:00+00,2015-02-08 00:08:00+00,470,W 20 St & 8 Ave,40.743453,46196,325,E 19 St & 3 Ave,40.736245,-73.984738,15585,Subscriber,1953.0,1
13226,NaN,-73.986831,NaN,392,2015-02-07 23:57:00+00,2015-02-08 00:03:00+00,474,5 Ave & E 29 St,40.745168,46198,325,E 19 St & 3 Ave,40.736245,-73.984738,15545,Subscriber,1986.0,1
13227,NaN,-73.986831,NaN,428,2015-02-07 23:57:00+00,2015-02-08 00:04:00+00,474,5 Ave & E 29 St,40.745168,46197,325,E 19 St & 3 Ave,40.736245,-73.984738,16395,Subscriber,1986.0,2
13228,NaN,-73.969053,NaN,1422,2015-02-07 23:57:00+00,2015-02-08 00:20:00+00,455,1 Ave & E 44 St,40.750020,46195,265,Stanton St & Chrystie St,40.722293,-73.991475,20184,Subscriber,1960.0,2
13229,NaN,-74.002150,NaN,548,2015-02-07 23:58:00+00,2015-02-08 00:08:00+00,368,Carmine St & 6 Ave,40.730386,46199,334,W 20 St & 7 Ave,40.742388,-73.997262,19540,Subscriber,1983.0,2
13230,NaN,-73.989780,NaN,917,2015-02-07 23:59:00+00,2015-02-08 00:15:00+00,439,E 4 St & 2 Ave,40.726281,46200,417,Barclay St & Church St,40.712912,-74.010202,20998,Subscriber,1965.0,2

### What are average trip duration during weekends?

In [12]:
test = '''SELECT AVG(tripduration) AS Average FROM htv210.citibike_feb_2015 
WHERE EXTRACT(DAY FROM starttime::date) IN (1,7)'''
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

      average  Unnamed: 1
0  662.942181         NaN

### 3) Can we do the same for weekday?

In [13]:
test = '''SELECT * FROM htv210.citibike_feb_2015 
WHERE EXTRACT(DAY FROM starttime::date) BETWEEN 2 AND 6
ORDER BY starttime'''
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

,the_geom,start_station_longitude,the_geom_webmercator,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,cartodb_id,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,NaN,-73.993915,NaN,199,2015-02-02 00:02:00+00,2015-02-02 00:05:00+00,442,W 27 St & 7 Ave,40.746647,6442,489,10 Ave & W 28 St,40.750664,-74.001768,20684,Subscriber,1992.0,1
1,NaN,-73.984267,NaN,418,2015-02-02 00:03:00+00,2015-02-02 00:10:00+00,326,E 11 St & 1 Ave,40.729538,6443,349,Rivington St & Ridge St,40.718502,-73.983299,16094,Subscriber,1964.0,2
2,NaN,-74.001670,NaN,276,2015-02-02 00:04:00+00,2015-02-02 00:09:00+00,279,Peck Slip & Front St,40.707873,6444,415,Pearl St & Hanover Square,40.704718,-74.009260,17362,Subscriber,1974.0,1
3,NaN,-73.992390,NaN,420,2015-02-02 00:06:00+00,2015-02-02 00:13:00+00,496,E 16 St & 5 Ave,40.737262,6445,237,E 11 St & 2 Ave,40.730473,-73.986724,15475,Subscriber,1992.0,2
4,NaN,-73.990026,NaN,304,2015-02-02 00:07:00+00,2015-02-02 00:12:00+00,477,W 41 St & 8 Ave,40.756405,6446,450,W 49 St & 8 Ave,40.762272,-73.987882,16272,Subscriber,1968.0,1
5,NaN,-73.978951,NaN,622,2015-02-02 00:08:00+00,2015-02-02 00:18:00+00,467,Dean St & 4 Ave,40.683125,6447,391,Clark St & Henry St,40.697601,-73.993446,16370,Subscriber,1979.0,1
6,NaN,-74.003664,NaN,371,2015-02-02 00:09:00+00,2015-02-02 00:15:00+00,434,9 Ave & W 18 St,40.743174,6448,482,W 15 St & 7 Ave,40.739355,-73.999318,19437,Subscriber,1963.0,1
7,NaN,-74.005628,NaN,477,2015-02-02 00:11:00+00,2015-02-02 00:19:00+00,330,Reade St & Broadway,40.714505,6449,2008,Little West St & 1 Pl,40.705693,-74.016777,21211,Subscriber,1982.0,1
8,NaN,-73.994811,NaN,743,2015-02-02 00:12:00+00,2015-02-02 00:25:00+00,521,8 Ave & W 31 St,40.750450,6450,423,W 54 St & 9 Ave,40.765849,-73.986905,21417,Subscriber,1978.0,2
9,NaN,-73.981656,NaN,599,2015-02-02 00:12:00+00,2015-02-02 00:22:00+00,504,1 Ave & E 15 St,40.732219,6451,453,W 22 St & 8 Ave,40.744751,-73.999154,15722,Subscriber,1956.0,1
10,NaN,-73.990741,NaN,345,2015-02-02 00:12:00+00,2015-02-02 00:18:00+00,285,Broadway & E 14 St,40.734546,6452,236,St Marks Pl & 2 Ave,40.728419,-73.987140,18972,Subscriber,1962.0,1
11,NaN,-73.983688,NaN,721,2015-02-02 00:13:00+00,2015-02-02 00:25:00+00,301,E 2 St & Avenue B,40.722174,6453,476,E 31 St & 3 Ave,40.743943,-73.979661,19628,Subscriber,1980.0,1
12,NaN,-74.001670,NaN,182,2015-02-02 00:13:00+00,2015-02-02 00:16:00+00,279,Peck Slip & Front St,40.707873,6454,376,John St & William St,40.708621,-74.007222,15169,Subscriber,1978.0,1
13,NaN,-73.980166,NaN,154,2015-02-02 00:13:00+00,2015-02-02 00:16:00+00,342,Columbia St & Rivington St,40.717400,6455,411,E 6 St & Avenue D,40.722281,-73.976687,17533,Subscriber,1997.0,1
14,NaN,-74.000040,NaN,435,2015-02-02 00:14:00+00,2015-02-02 00:21:00+00,470,W 20 St & 8 Ave,40.743453,6456,491,E 24 St & Park Ave S,40.740964,-73.986022,19761,Subscriber,1983.0,1
15,NaN,-73.987140,NaN,310,2015-02-02 00:15:00+00,2015-02-02 00:20:00+00,236,St Marks Pl & 2 Ave,40.728419,6457,393,E 5 St & Avenue C,40.722992,-73.979955,17267,Subscriber,1993.0,1
16,NaN,-74.000040,NaN,1274,2015-02-02 00:16:00+00,2015-02-02 00:37:00+00,470,W 20 St & 8 Ave,40.743453,6458,470,W 20 St & 8 Ave,40.743453,-74.000040,18691,Subscriber,1964.0,1
17,NaN,-73.983390,NaN,642,2015-02-02 00:18:00+00,2015-02-02 00:29:00+00,485,W 37 St & 5 Ave,40.750380,6459,174,E 25 St & 1 Ave,40.738177,-73.977387,17106,Subscriber,1977.0,1
18,NaN,-73.997044,NaN,256,2015-02-02 00:18:00+00,2015-02-02 00:22:00+00,345,W 13 St & 6 Ave,40.736494,6460,483,E 12 St & 3 Ave,40.732233,-73.988900,20009,Subscriber,1973.0,1
19,NaN,-74.001768,NaN,334,2015-02-02 00:19:00+00,2015-02-02 00:25:00+00,489,10 Ave & W 28 St,40.750664,6461,442,W 27 St & 7 Ave,40.746647,-73.993915,18777,Subscriber,1979.0,1
20,NaN,-73.979738,NaN,90,2015-02-02 00:19:00+00,2015-02-02 00:20:00+00,507,E 25 St & 2 Ave,40.739126,6462,174,E 25 St & 1 Ave,40.738177,-73.977387,15357,Subscriber,1989.0,1
21,NaN,-74.002939,NaN,203,2015-02-02 00:20:00+00,2015-02-02 00:23:00+00,380,W 4 St & 7 Ave S,40.734011,6463,405,Washington St & Gansevoort St,40.739323,-74.008119,18487,Subscriber,1983.0,1
22,NaN,-73.997262,NaN,649,2015-02-02 00:22:00+00,2015-02-02 00:32:00+00,334,W 20 St & 7 Ave,40.742388,6464,439,E 4 St & 2 Ave,40.726281,-73.989780,20863,Subscriber,1981.0,1
23,NaN,-73.996674,NaN,319,2015-02-02 00:23:00+00,2015-02-02 00:29:00+00,508,W 46 St & 11 Ave,40.763414,6465,448,W 37 St & 10 Ave,40.756604,-73.997901,16539,Subscriber,1970.0,1
24,NaN,-73.987834,NaN,154,2015-02-02 00:27:00+00,2015-02-02 00:30:00+00,428,E 3 St & 1 Ave,40.724677,6466,301,E 2 St & Avenue B,40.722174,-73.983688,18737,Subscriber,1961.0,1
25,NaN,-73.991930,NaN,550,2015-02-02 00:28:00+00,2015-02-02 00:37:00+00,331,Pike St & Monroe St,40.711731,6467,195,Liberty St & Broadway,40.709056,-74.010434,17797,Subscriber,1980.0,2
26,NaN,-73.990985,NaN,268,2015-02-02 00:29:00+00,2015-02-02 00:34:00+00,529,W 42 St & 8 Ave,40.757570,6468,478,11 Ave & W 41 St,40.760301,-73.998842,20638,Subscriber,1990.0,1
27,NaN,-73.971297,NaN,153,2015-02-02 00:29:00+00,2015-02-02 00:31:00+00,421,Clermont Ave & Park Ave,40.695734,6469,366,Clinton Ave & Myrtle Ave,40.693261,-73.968896,17636,Subscriber,1989.0,1
28,NaN,-74.002638,NaN,309,2015-02-02 00:31:00+00,2015-02-02 00:36:00+00,284,Greenwich Ave & 8 Ave,40.739017,6470,494,W 26 St & 8 Ave,40.747348,-73.997236,18472,Subscriber,1982.0,1
29,NaN,-74.000271,NaN,138,2015-02-02 00:33:00+00,2015-02-02 00:35:00+00,383,Greenwich Ave & Charles St,40.735238,6471,252,MacDougal St & Washington Sq,40.732264,-73.998522,17456,Subscriber,1968.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32939,NaN,-73.986580,NaN,321,2015-02-06 23:47:00+00,2015-02-06 23:52:00+00,465,Broadway & W 41 St,40.755136,39381,492,W 33 St & 7 Ave,40.750200,-73.990931,18249,Subscriber,1957.0,1
32940,NaN,-73.991382,NaN,449,2015-02-06 23:48:00+00,2015-02-06 23:55:00+00,523,W 38 St & 8 Ave,40.754666,39382,318,E 43 St & Vanderbilt Ave,40.753202,-73.977987,19146,Subscriber,1972.0,2
32941,NaN,-74.001971,NaN,120,2015-02-06 23:48:00+00,2015-02-06 23:50:00+00,509,9 Ave & W 22 St,40.745497,39383,434,9 Ave & W 18 St,40.743174,-74.003664,15313,Subscriber,1984.0,1
32942,NaN,-73.989551,NaN,501,2015-02-06 23:49:00+00,2015-02-06 23:57:00+00,402,Broadway & E 22 St,40.740343,39385,403,E 2 St & 2 Ave,40.725029,-73.990697,18929,Subscriber,1966.0,1
32943,NaN,-73.976682,NaN,977,2015-02-06 23:49:00+00,2015-02-07 00:05:00+00,274,Lafayette Ave & Fort Greene Pl,40.686919,39384,2002,Wythe Ave & Metropolitan Ave,40.716887,-73.963198,18469,Subscriber,1979.0,1
32944,NaN,-73.978095,NaN,441,2015-02-06 23:50:00+00,2015-02-06 23:58:00+00,545,E 23 St & 1 Ave,40.736502,39386,402,Broadway & E 22 St,40.740343,-73.989551,19009,Subscriber,1987.0,1
32945,NaN,-73.984738,NaN,388,2015-02-06 23:50:00+00,2015-02-06 23:57:00+00,325,E 19 St & 3 Ave,40.736245,39387,438,St Marks Pl & 1 Ave,40.727791,-73.985649,17102,Subscriber,1984.0,1
32946,NaN,-73.989551,NaN,284,2015-02-06 23:51:00+00,2015-02-06 23:55:00+00,402,Broadway & E 22 St,40.740343,39389,472,E 32 St & Park Ave,40.745712,-73.981948,15377,Subscriber,1989.0,1
32947,NaN,-74.000271,NaN,271,2015-02-06 23:51:00+00,2015-02-06 23:56:00+00,383,Greenwich Ave & Charles St,40.735238,39390,435,W 21 St & 6 Ave,40.741740,-73.994156,17844,Subscriber,1984.0,1
32948,NaN,-73.990765,NaN,607,2015-02-06 23:51:00+00,2015-02-07 00:01:00+00,293,Lafayette St & E 8 St,40.730287,39388,266,Avenue D & E 8 St,40.723684,-73.975748,18686,Subscriber,1972.0,2
32949,NaN,-73.991908,NaN,572,2015-02-06 23:52:00+00,2015-02-07 00:01:00+00,361,Allen St & Hester St,40.716059,39391,438,St Marks Pl & 1 Ave,40.727791,-73.985649,21040,Subscriber,1987.0,1
32950,NaN,-73.992390,NaN,267,2015-02-06 23:53:00+00,2015-02-06 23:58:00+00,496,E 16 St & 5 Ave,40.737262,39394,435,W 21 St & 6 Ave,40.741740,-73.994156,16934,Subscriber,1983.0,1
32951,NaN,-73.987520,NaN,498,2015-02-06 23:53:00+00,2015-02-07 00:01:00+00,503,E 20 St & Park Ave,40.738274,39392,380,W 4 St & 7 Ave S,40.734011,-74.002939,19480,Subscriber,1981.0,1
32952,NaN,-73.981013,NaN,425,2015-02-06 23:53:00+00,2015-02-07 00:00:00+00,324,DeKalb Ave & Hudson Ave,40.689888,39393,258,DeKalb Ave & Vanderbilt Ave,40.689407,-73.968855,21130,Subscriber,1978.0,1
32953,NaN,-73.980144,NaN,165,2015-02-06 23:53:00+00,2015-02-06 23:56:00+00,484,W 44 St & 5 Ave,40.755003,39395,318,E 43 St & Vanderbilt Ave,40.753202,-73.977987,20745,Subscriber,1968.0,1
32954,NaN,-73.990093,NaN,489,2015-02-06 23:54:00+00,2015-02-07 00:02:00+00,497,E 17 St & Broadway,40.737050,39399,486,Broadway & W 29 St,40.746201,-73.988557,17370,Subscriber,1959.0,1
32955,NaN,-73.967597,NaN,751,2015-02-06 23:54:00+00,2015-02-07 00:06:00+00,464,E 56 St & 3 Ave,40.759345,39396,507,E 25 St & 2 Ave,40.739126,-73.979738,16811,Subscriber,1969.0,1
32956,NaN,-73.983688,NaN,747,2015-02-06 23:54:00+00,2015-02-07 00:07:00+00,301,E 2 St & Avenue B,40.722174,39397,476,E 31 St & 3 Ave,40.743943,-73.979661,21259,Subscriber,1980.0,1
32957,NaN,-73.989780,NaN,511,2015-02-06 23:54:00+00,2015-02-07 00:03:00+00,439,E 4 St & 2 Ave,40.726281,39398,375,Mercer St & Bleecker St,40.726795,-73.996951,15618,Subscriber,1993.0,1
32958,NaN,-73.980420,NaN,649,2015-02-06 23:55:00+00,2015-02-07 00:06:00+00,510,W 51 St & 6 Ave,40.760660,39401,512,W 29 St & 9 Ave,40.750073,-73.998393,18303,Subscriber,1986.0,1
32959,NaN,-73.998004,NaN,377,2015-02-06 23:55:00+00,2015-02-07 00:01:00+00,254,W 11 St & 6 Ave,40.735324,39402,453,W 22 St & 8 Ave,40.744751,-73.999154,20360,Subscriber,1990.0,1
32960,NaN,-73.981656,NaN,1183,2015-02-06 23:55:00+00,2015-02-07 00:14:00+00,504,1 Ave & E 15 St,40.732219,39400,295,Pike St & E Broadway,40.714067,-73.992939,19430,Subscriber,1984.0,1
32961,NaN,-73.999318,NaN,298,2015-02-06 23:56:00+00,2015-02-07 00:01:00+00,482,W 15 St & 7 Ave,40.739355,39404,368,Carmine St & 6 Ave,40.730386,-74.002150,21575,Subscriber,1983.0,1
32962,NaN,-74.000040,NaN,485,2015-02-06 23:56:00+00,2015-02-07 00:04:00+00,470,W 20 St & 8 Ave,40.743453,39403,491,E 24 St & Park Ave S,40.740964,-73.986022,21564,Subscriber,1983.0,1
32963,NaN,-73.982050,NaN,648,2015-02-06 23:57:00+00,2015-02-07 00:07:00+00,461,E 20 St & 2 Ave,40.735877,39405,346,Bank St & Hudson St,40.736529,-74.006180,21014,Subscriber,1983.0,1
32964,NaN,-73.998522,NaN,1261,2015-02-06 23:58:00+00,2015-02-07 00:19:00+00,252,MacDougal St & Washington Sq,40.732264,39406,450,W 49 St & 8 Ave,40.762272,-73.987882,17797,Subscriber,1989.0,2
32965,NaN,-73.981013,NaN,331,2015-02-06 23:58:00+00,2015-02-07 00:04:00+00,324,DeKalb Ave & Hudson Ave,40.689888,39407,270,Adelphi St & Myrtle Ave,40.693083,-73.971789,16975,Subscriber,1984.0,1
32966,NaN,-73.989978,NaN,329,2015-02-06 23:59:00+00,2015-02-07 00:04:00+00,401,Allen St & Rivington St,40.720196,39410,301,E 2 St & Avenue B,40.722174,-73.983688,15426,Subscriber,1987.0,1
32967,NaN,-73.997044,NaN,629,2015-02-06 23:59:00+00,2015-02-07 00:10:00+00,345,W 13 St & 6 Ave,40.736494,39408,236,St Marks Pl & 2 Ave,40.728419,-73.987140,19820,Subscriber,1982.0,1
32968,NaN,-73.996375,NaN,492,2015-02-06 23:59:00+00,2015-02-07 00:07:00+00,263,Elizabeth St & Hester St,40.717290,39409,502,Henry St & Grand St,40.714215,-73.981346,19487,Subscriber,1966.0,1

In [14]:
test = '''SELECT AVG(tripduration) AS Average FROM htv210.citibike_feb_2015 
WHERE EXTRACT(DAY FROM starttime::date) BETWEEN 2 AND 6'''
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

      average  Unnamed: 1
0  681.052292         NaN

## Task 3

### 1) Showing the list of start station locations

In [15]:
test = '''SELECT start_station_name FROM htv210.citibike_feb_2015 
GROUP BY start_station_name'''
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

                start_station_name  Unnamed: 1
0             E 30 St & Park Ave S         NaN
1          Pearl St & Anchorage Pl         NaN
2                  W 56 St & 6 Ave         NaN
3                   West Thames St         NaN
4          Bank St & Washington St         NaN
5                  8 Ave & W 52 St         NaN
6               E 11 St & Broadway         NaN
7         DeKalb Ave & Skillman St         NaN
8    Atlantic Ave & Fort Greene Pl         NaN
9                Avenue D & E 8 St         NaN
10            S 3 St & Bedford Ave         NaN
11          W Broadway & Spring St         NaN
12                 2 Ave & E 31 St         NaN
13                 E 33 St & 5 Ave         NaN
14        MacDougal St & Prince St         NaN
15    Clermont Ave & Lafayette Ave         NaN
16          Barclay St & Church St         NaN
17          Forsyth St & Broome St         NaN
18                 W 13 St & 6 Ave         NaN
19              E 20 St & Park Ave         NaN
20                 W 17 St & 8 Ave         NaN
21               E 2 St & Avenue B         NaN
22                 E 33 St & 2 Ave         NaN
23                 W 18 St & 6 Ave         NaN
24             Old Slip & Front St         NaN
25                 1 Ave & E 44 St         NaN
26        Willoughby Ave & Hall St         NaN
27                 W 20 St & 7 Ave         NaN
28                 E 43 St & 2 Ave         NaN
29           West St & Chambers St         NaN
..                             ...         ...
297               12 Ave & W 40 St         NaN
298        Centre St & Chambers St         NaN
299                W 33 St & 7 Ave         NaN
300          Pershing Square South         NaN
301         Hicks St & Montague St         NaN
302        University Pl & E 14 St         NaN
303        Fulton St & Rockwell Pl         NaN
304    Lafayette Ave & St James Pl         NaN
305        Emerson Pl & Myrtle Ave         NaN
306                E 56 St & 3 Ave         NaN
307        Watts St & Greenwich St         NaN
308                W 44 St & 5 Ave         NaN
309                6 Ave & W 33 St         NaN
310              E 9 St & Avenue C         NaN
311               11 Ave & W 59 St         NaN
312        W 16 St & The High Line         NaN
313          Howard St & Centre St         NaN
314                2 Ave & E 58 St         NaN
315              E 5 St & Avenue C         NaN
316       Fulton St & Clermont Ave         NaN
317    Cadman Plaza E & Tillary St         NaN
318      Pearl St & Hanover Square         NaN
319          LaGuardia Pl & W 3 St         NaN
320                5 Ave & E 29 St         NaN
321                W 21 St & 6 Ave         NaN
322   Wythe Ave & Metropolitan Ave         NaN
323                W 11 St & 6 Ave         NaN
324            St Marks Pl & 1 Ave         NaN
325                W 22 St & 8 Ave         NaN
326         Railroad Ave & Kay Ave         NaN

[327 rows x 2 columns]

### 2) Showing the number of trips started per station

In [20]:
test = '''SELECT start_station_name, COUNT(cartodb_id) FROM htv210.citibike_feb_2015 
GROUP BY start_station_name'''
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

                start_station_name  count
0             E 30 St & Park Ave S    227
1          Pearl St & Anchorage Pl     54
2                  W 56 St & 6 Ave    164
3                   West Thames St    107
4          Bank St & Washington St    125
5                  8 Ave & W 52 St    133
6               E 11 St & Broadway    115
7         DeKalb Ave & Skillman St     10
8    Atlantic Ave & Fort Greene Pl     36
9                Avenue D & E 8 St     38
10            S 3 St & Bedford Ave     13
11          W Broadway & Spring St    159
12                 2 Ave & E 31 St    302
13                 E 33 St & 5 Ave    213
14        MacDougal St & Prince St    247
15    Clermont Ave & Lafayette Ave     25
16          Barclay St & Church St    244
17          Forsyth St & Broome St    212
18                 W 13 St & 6 Ave    257
19              E 20 St & Park Ave    218
20                 W 17 St & 8 Ave    288
21               E 2 St & Avenue B    199
22                 E 33 St & 2 Ave    319
23                 W 18 St & 6 Ave    327
24             Old Slip & Front St     60
25                 1 Ave & E 44 St    110
26        Willoughby Ave & Hall St     35
27                 W 20 St & 7 Ave    190
28                 E 43 St & 2 Ave     86
29           West St & Chambers St    162
..                             ...    ...
297               12 Ave & W 40 St     91
298        Centre St & Chambers St    159
299                W 33 St & 7 Ave    309
300          Pershing Square South    362
301         Hicks St & Montague St     64
302        University Pl & E 14 St    341
303        Fulton St & Rockwell Pl     37
304    Lafayette Ave & St James Pl     32
305        Emerson Pl & Myrtle Ave     30
306                E 56 St & 3 Ave     41
307        Watts St & Greenwich St     73
308                W 44 St & 5 Ave    137
309                6 Ave & W 33 St    296
310              E 9 St & Avenue C    201
311               11 Ave & W 59 St    120
312        W 16 St & The High Line    186
313          Howard St & Centre St    124
314                2 Ave & E 58 St     64
315              E 5 St & Avenue C    142
316       Fulton St & Clermont Ave     27
317    Cadman Plaza E & Tillary St     22
318      Pearl St & Hanover Square     97
319          LaGuardia Pl & W 3 St    203
320                5 Ave & E 29 St    230
321                W 21 St & 6 Ave    519
322   Wythe Ave & Metropolitan Ave     45
323                W 11 St & 6 Ave    108
324            St Marks Pl & 1 Ave    156
325                W 22 St & 8 Ave    218
326         Railroad Ave & Kay Ave      7

[327 rows x 2 columns]

###  3）but only for stations within 500m of Time Square!

In [19]:
test = '''SELECT start_station_name, COUNT(cartodb_id), 
(SQRT(POWER(start_station_latitude - 40.7577,2) + POWER(start_station_longitude + 73.9857,2))*111000) AS DIST
FROM htv210.citibike_feb_2015
WHERE (SQRT(POWER(start_station_latitude - 40.7577,2) + POWER(start_station_longitude + 73.9857,2))*111000) < 502
GROUP BY start_station_name, start_station_latitude, start_station_longitude
ORDER BY DIST'''
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

   start_station_name  count        dist
0  Broadway & W 41 St    251  300.956692
1     W 45 St & 6 Ave    141  325.239186
2  Broadway & W 49 St    213  356.328056
3     W 45 St & 8 Ave    141  366.834679
4     W 43 St & 6 Ave    112  389.199116
5     W 41 St & 8 Ave    507  501.245674

## Task 4
### 1) Find the station that had the longest average trip duration during weekends and within 500m of TimeSquare

In [18]:
test = '''SELECT start_station_name, AVG(tripduration) AS Average, 
(SQRT(POWER(start_station_latitude - 40.7577,2) + POWER(start_station_longitude + 73.9857,2))*111000) AS DIST
FROM htv210.citibike_feb_2015
WHERE (SQRT(POWER(start_station_latitude - 40.7577,2) + POWER(start_station_longitude + 73.9857,2))*111000) < 502
AND EXTRACT(DAY FROM starttime::date) IN (1,7)
GROUP BY start_station_name, start_station_latitude, start_station_longitude
ORDER BY Average DESC
LIMIT 1'''
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

   start_station_name      average        dist
0  Broadway & W 49 St  1010.104167  356.328056

# extra credit: make the function python 2 and 3 compatible so that it works on the  PUI2016_Python3 kernel

## create lines for trips started from stations within 500m of Times. Squares and lasted less than 2 hours. The number of trips per each pair of stations are output as attributes of these lines.

In [21]:
test = '''SELECT start_station_name, end_station_name, tripduration, COUNT(cartodb_id) AS COUNT,
(SQRT(POWER(start_station_latitude - 40.7577,2) + POWER(start_station_longitude + 73.9857,2))*111000) AS DIST
FROM htv210.citibike_feb_2015
WHERE (SQRT(POWER(start_station_latitude - 40.7577,2) + POWER(start_station_longitude + 73.9857,2))*111000) < 502
AND tripduration < 7200
GROUP BY start_station_name, end_station_name, start_station_latitude, start_station_longitude, tripduration
ORDER BY COUNT DESC, start_station_name, tripduration DESC'''
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

,start_station_name,end_station_name,tripduration,count,dist
0,Broadway & W 49 St,11 Ave & W 41 St,651,2,356.328056
1,Broadway & W 49 St,E 47 St & Park Ave,373,2,356.328056
2,W 41 St & 8 Ave,E 47 St & Park Ave,671,2,501.245674
3,W 41 St & 8 Ave,E 30 St & Park Ave S,502,2,501.245674
4,W 41 St & 8 Ave,Pershing Square South,459,2,501.245674
5,W 41 St & 8 Ave,11 Ave & W 41 St,423,2,501.245674
6,W 41 St & 8 Ave,W 43 St & 10 Ave,256,2,501.245674
7,W 41 St & 8 Ave,Broadway & W 36 St,203,2,501.245674
8,W 41 St & 8 Ave,W 41 St & 8 Ave,93,2,501.245674
9,W 45 St & 6 Ave,W 45 St & 8 Ave,259,2,325.239186
10,W 45 St & 8 Ave,8 Ave & W 33 St,370,2,366.834679
11,W 45 St & 8 Ave,8 Ave & W 52 St,267,2,366.834679
12,W 45 St & 8 Ave,8 Ave & W 52 St,218,2,366.834679
13,Broadway & W 41 St,Pearl St & Anchorage Pl,2716,1,300.956692
14,Broadway & W 41 St,Cherry St,2217,1,300.956692
15,Broadway & W 41 St,Forsyth St & Canal St,2031,1,300.956692
16,Broadway & W 41 St,Elizabeth St & Hester St,1870,1,300.956692
17,Broadway & W 41 St,E 58 St & 3 Ave,1841,1,300.956692
18,Broadway & W 41 St,Broadway & W 49 St,1788,1,300.956692
19,Broadway & W 41 St,Allen St & Rivington St,1730,1,300.956692
20,Broadway & W 41 St,Washington Pl & Broadway,1711,1,300.956692
21,Broadway & W 41 St,Duane St & Greenwich St,1693,1,300.956692
22,Broadway & W 41 St,E 14 St & Avenue B,1655,1,300.956692
23,Broadway & W 41 St,Suffolk St & Stanton St,1581,1,300.956692
24,Broadway & W 41 St,E 14 St & Avenue B,1502,1,300.956692
25,Broadway & W 41 St,Broadway & W 41 St,1471,1,300.956692
26,Broadway & W 41 St,Allen St & Hester St,1464,1,300.956692
27,Broadway & W 41 St,Forsyth St & Broome St,1462,1,300.956692
28,Broadway & W 41 St,W 4 St & 7 Ave S,1447,1,300.956692
29,Broadway & W 41 St,Forsyth St & Broome St,1405,1,300.956692
...,...,...,...,...,...
1321,W 45 St & 8 Ave,8 Ave & W 52 St,338,1,366.834679
1322,W 45 St & 8 Ave,W 51 St & 6 Ave,337,1,366.834679
1323,W 45 St & 8 Ave,W 33 St & 7 Ave,334,1,366.834679
1324,W 45 St & 8 Ave,8 Ave & W 33 St,323,1,366.834679
1325,W 45 St & 8 Ave,W 51 St & 6 Ave,318,1,366.834679
1326,W 45 St & 8 Ave,8 Ave & W 52 St,311,1,366.834679
1327,W 45 St & 8 Ave,8 Ave & W 52 St,274,1,366.834679
1328,W 45 St & 8 Ave,W 43 St & 10 Ave,271,1,366.834679
1329,W 45 St & 8 Ave,11 Ave & W 41 St,260,1,366.834679
1330,W 45 St & 8 Ave,W 42 St & 8 Ave,260,1,366.834679
1331,W 45 St & 8 Ave,Broadway & W 41 St,246,1,366.834679
1332,W 45 St & 8 Ave,8 Ave & W 52 St,246,1,366.834679
1333,W 45 St & 8 Ave,W 47 St & 10 Ave,238,1,366.834679
1334,W 45 St & 8 Ave,8 Ave & W 52 St,228,1,366.834679
1335,W 45 St & 8 Ave,W 47 St & 10 Ave,224,1,366.834679
1336,W 45 St & 8 Ave,W 43 St & 10 Ave,218,1,366.834679
1337,W 45 St & 8 Ave,Broadway & W 41 St,218,1,366.834679
1338,W 45 St & 8 Ave,W 39 St & 9 Ave,216,1,366.834679
1339,W 45 St & 8 Ave,Broadway & W 49 St,207,1,366.834679
1340,W 45 St & 8 Ave,W 39 St & 9 Ave,205,1,366.834679
1341,W 45 St & 8 Ave,8 Ave & W 52 St,202,1,366.834679
1342,W 45 St & 8 Ave,W 39 St & 9 Ave,197,1,366.834679
1343,W 45 St & 8 Ave,8 Ave & W 52 St,188,1,366.834679
1344,W 45 St & 8 Ave,W 43 St & 10 Ave,180,1,366.834679
1345,W 45 St & 8 Ave,8 Ave & W 52 St,178,1,366.834679
1346,W 45 St & 8 Ave,W 45 St & 8 Ave,162,1,366.834679
1347,W 45 St & 8 Ave,W 47 St & 10 Ave,141,1,366.834679
1348,W 45 St & 8 Ave,W 45 St & 8 Ave,123,1,366.834679
1349,W 45 St & 8 Ave,9 Ave & W 45 St,112,1,366.834679
1350,W 45 St & 8 Ave,W 45 St & 8 Ave,90,1,366.834679